// <auto-generated />
using System;
using BackendApi.Modules.Returns.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BackendApi.Modules.Returns.Persistence.Migrations
{
    [DbContext(typeof(ReturnsDbContext))]
    partial class ReturnsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("returns")
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BackendApi.Modules.Returns.Entities.Inspection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InspectorAccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("MarketCode")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<Guid>("ReturnRequestId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("State")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("citext")
                        .HasDefaultValue("pending");

                    b.HasKey("Id");

                    b.HasIndex("ReturnRequestId");

                    b.HasIndex("MarketCode", "StartedAt")
                        .HasDatabaseName("IX_returns_inspections_market_started");

                    b.ToTable("inspections", "returns", t =>
                        {
                            t.HasCheckConstraint("CK_returns_inspections_state_enum", "\"State\" IN ('pending','in_progress','complete')");
                        });
                });

            modelBuilder.Entity("BackendApi.Modules.Returns.Entities.InspectionLine", b =>
                {
                    b.Property<Guid>("InspectionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ReturnLineId")
                        .HasColumnType("uuid");

                    b.Property<int>("DefectiveQty")
                        .HasColumnType("integer");

                    b.Property<string>("MarketCode")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<string>("PhotosJson")
                        .HasColumnType("jsonb");

                    b.Property<int>("SellableQty")
                        .HasColumnType("integer");

                    b.HasKey("InspectionId", "ReturnLineId");

                    b.HasIndex("ReturnLineId");

                    b.ToTable("inspection_lines", "returns", t =>
                        {
                            t.HasCheckConstraint("CK_returns_inspection_lines_qty_non_negative", "\"SellableQty\" >= 0 AND \"DefectiveQty\" >= 0");
                        });
                });

            modelBuilder.Entity("BackendApi.Modules.Returns.Entities.Refund", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("AmountMinor")
                        .HasColumnType("bigint");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<string>("CapturedTransactionId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text");

                    b.Property<string>("GatewayRef")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("InitiatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ManualBankName")
                        .HasColumnType("text");

                    b.Property<string>("ManualBeneficiaryName")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ManualConfirmedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ManualConfirmedByAccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("ManualIban")
                        .HasColumnType("text");

                    b.Property<string>("ManualReference")
                        .HasColumnType("text");

                    b.Property<string>("MarketCode")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<DateTimeOffset?>("NextRetryAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProviderId")
                        .HasColumnType("citext");

                    b.Property<long>("RestockingFeeMinor")
                        .HasColumnType("bigint");

                    b.Property<Guid>("ReturnRequestId")
                        .HasColumnType("uuid");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("State")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("citext")
                        .HasDefaultValue("pending");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("NextRetryAt")
                        .HasDatabaseName("IX_returns_refunds_retry_pending")
                        .HasFilter("\"State\" = 'failed' AND \"NextRetryAt\" IS NOT NULL");

                    b.HasIndex("ReturnRequestId")
                        .IsUnique()
                        .HasDatabaseName("IX_returns_refunds_request_active_unique")
                        .HasFilter("\"State\" IN ('pending','in_progress','pending_manual_transfer','completed')");

                    b.HasIndex("State")
                        .HasDatabaseName("IX_returns_refunds_state");

                    b.HasIndex("MarketCode", "State")
                        .HasDatabaseName("IX_returns_refunds_market_state");

                    b.ToTable("refunds", "returns", t =>
                        {
                            t.HasCheckConstraint("CK_returns_refunds_amount_non_negative", "\"AmountMinor\" >= 0");

                            t.HasCheckConstraint("CK_returns_refunds_attempts_non_negative", "\"Attempts\" >= 0");

                            t.HasCheckConstraint("CK_returns_refunds_restocking_fee_non_negative", "\"RestockingFeeMinor\" >= 0");

                            t.HasCheckConstraint("CK_returns_refunds_state_enum", "\"State\" IN ('pending','in_progress','pending_manual_transfer','completed','failed')");
                        });
                });

            modelBuilder.Entity("BackendApi.Modules.Returns.Entities.RefundLine", b =>
                {
                    b.Property<Guid>("RefundId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ReturnLineId")
                        .HasColumnType("uuid");

                    b.Property<long>("LineAmountMinor")
                        .HasColumnType("bigint");

                    b.Property<long>("LineDiscountMinor")
                        .HasColumnType("bigint");

                    b.Property<long>("LineSubtotalMinor")
                        .HasColumnType("bigint");

                    b.Property<long>("LineTaxMinor")
                        .HasColumnType("bigint");

                    b.Property<string>("MarketCode")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<int>("Qty")
                        .HasColumnType("integer");

                    b.Property<int>("TaxRateBp")
                        .HasColumnType("integer");

                    b.Property<long>("UnitPriceMinor")
                        .HasColumnType("bigint");

                    b.HasKey("RefundId", "ReturnLineId");

                    b.HasIndex("ReturnLineId");

                    b.ToTable("refund_lines", "returns", t =>
                        {
                            t.HasCheckConstraint("CK_returns_refund_lines_amounts_non_negative", "\"LineSubtotalMinor\" >= 0 AND \"LineDiscountMinor\" >= 0 AND \"LineTaxMinor\" >= 0 AND \"LineAmountMinor\" >= 0");

                            t.HasCheckConstraint("CK_returns_refund_lines_qty_positive", "\"Qty\" > 0");

                            t.HasCheckConstraint("CK_returns_refund_lines_tax_rate_bounds", "\"TaxRateBp\" >= 0 AND \"TaxRateBp\" <= 10000");
                        });
                });

            modelBuilder.Entity("BackendApi.Modules.Returns.Entities.ReturnLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("ApprovedQty")
                        .HasColumnType("integer");

                    b.Property<int?>("DefectiveQty")
                        .HasColumnType("integer");

                    b.Property<string>("LineReasonCode")
                        .HasColumnType("citext");

                    b.Property<string>("MarketCode")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<Guid>("OrderLineId")
                        .HasColumnType("uuid");

                    b.Property<long>("OriginalDiscountMinor")
                        .HasColumnType("bigint");

                    b.Property<int>("OriginalQty")
                        .HasColumnType("integer");

                    b.Property<long>("OriginalTaxMinor")
                        .HasColumnType("bigint");

                    b.Property<int?>("ReceivedQty")
                        .HasColumnType("integer");

                    b.Property<int>("RequestedQty")
                        .HasColumnType("integer");

                    b.Property<Guid>("ReturnRequestId")
                        .HasColumnType("uuid");

                    b.Property<int?>("SellableQty")
                        .HasColumnType("integer");

                    b.Property<int>("TaxRateBp")
                        .HasColumnType("integer");

                    b.Property<long>("UnitPriceMinor")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OrderLineId");

                    b.HasIndex("ReturnRequestId");

                    b.HasIndex("MarketCode", "OrderLineId")
                        .HasDatabaseName("IX_returns_return_lines_market_order_line");

                    b.ToTable("return_lines", "returns", t =>
                        {
                            t.HasCheckConstraint("CK_returns_return_lines_approved_qty_bounds", "\"ApprovedQty\" IS NULL OR (\"ApprovedQty\" >= 0 AND \"ApprovedQty\" <= \"RequestedQty\")");

                            t.HasCheckConstraint("CK_returns_return_lines_inspection_qty_balance", "(\"SellableQty\" IS NULL AND \"DefectiveQty\" IS NULL) OR (\"ReceivedQty\" IS NOT NULL AND \"SellableQty\" IS NOT NULL AND \"DefectiveQty\" IS NOT NULL AND \"SellableQty\" + \"DefectiveQty\" = \"ReceivedQty\")");

                            t.HasCheckConstraint("CK_returns_return_lines_original_discount_non_negative", "\"OriginalDiscountMinor\" >= 0");

                            t.HasCheckConstraint("CK_returns_return_lines_original_qty_positive", "\"OriginalQty\" > 0");

                            t.HasCheckConstraint("CK_returns_return_lines_original_tax_non_negative", "\"OriginalTaxMinor\" >= 0");

                            t.HasCheckConstraint("CK_returns_return_lines_received_qty_bounds", "\"ReceivedQty\" IS NULL OR (\"ApprovedQty\" IS NOT NULL AND \"ReceivedQty\" >= 0 AND \"ReceivedQty\" <= \"ApprovedQty\")");

                            t.HasCheckConstraint("CK_returns_return_lines_requested_qty_positive", "\"RequestedQty\" > 0");

                            t.HasCheckConstraint("CK_returns_return_lines_tax_rate_bounds", "\"TaxRateBp\" >= 0 AND \"TaxRateBp\" <= 10000");

                            t.HasCheckConstraint("CK_returns_return_lines_unit_price_non_negative", "\"UnitPriceMinor\" >= 0");
                        });
                });

            modelBuilder.Entity("BackendApi.Modules.Returns.Entities.ReturnPhoto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("BlobKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MarketCode")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<string>("Mime")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<Guid?>("ReturnRequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("ReturnRequestId");

                    b.HasIndex("MarketCode", "UploadedAt")
                        .HasDatabaseName("IX_returns_return_photos_market_uploaded");

                    b.ToTable("return_photos", "returns", t =>
                        {
                            t.HasCheckConstraint("CK_returns_return_photos_size_positive", "\"SizeBytes\" > 0");
                        });
                });

            modelBuilder.Entity("BackendApi.Modules.Returns.Entities.ReturnPolicy", b =>
                {
                    b.Property<string>("MarketCode")
                        .HasColumnType("citext");

                    b.Property<int?>("AutoApproveUnderDays")
                        .HasColumnType("integer");

                    b.Property<int>("RestockingFeeBp")
                        .HasColumnType("integer");

                    b.Property<int>("ReturnWindowDays")
                        .HasColumnType("integer");

                    b.Property<bool>("ShippingRefundOnFullOnly")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByAccountId")
                        .HasColumnType("uuid");

                    b.HasKey("MarketCode");

                    b.ToTable("return_policies", "returns", t =>
                        {
                            t.HasCheckConstraint("CK_returns_return_policies_restocking_fee_bounds", "\"RestockingFeeBp\" >= 0 AND \"RestockingFeeBp\" <= 10000");

                            t.HasCheckConstraint("CK_returns_return_policies_window_non_negative", "\"ReturnWindowDays\" >= 0");
                        });
                });

            modelBuilder.Entity("BackendApi.Modules.Returns.Entities.ReturnRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("AdminNotes")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerNotes")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DecidedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DecidedByAccountId")
                        .HasColumnType("uuid");

                    b.Property<bool>("ForceRefund")
                        .HasColumnType("boolean");

                    b.Property<string>("MarketCode")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<string>("ReturnNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("State")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("citext")
                        .HasDefaultValue("pending_review");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("IX_returns_return_requests_order");

                    b.HasIndex("ReturnNumber")
                        .IsUnique();

                    b.HasIndex("AccountId", "SubmittedAt")
                        .HasDatabaseName("IX_returns_return_requests_account_submitted");

                    b.HasIndex("MarketCode", "State", "SubmittedAt")
                        .HasDatabaseName("IX_returns_return_requests_market_state_submitted");

                    b.ToTable("return_requests", "returns", t =>
                        {
                            t.HasCheckConstraint("CK_returns_return_requests_state_enum", "\"State\" IN ('pending_review','approved','approved_partial','rejected','received','inspected','refunded','refund_failed')");
                        });
                });

            modelBuilder.Entity("BackendApi.Modules.Returns.Entities.ReturnStateTransition", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid?>("ActorAccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContextJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("FromState")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<Guid?>("InspectionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Machine")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<string>("MarketCode")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<Guid?>("RefundId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ReturnRequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("ToState")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.HasKey("Id");

                    b.HasIndex("MarketCode", "OccurredAt")
                        .HasDatabaseName("IX_returns_state_transitions_market_occurred");

                    b.HasIndex("ReturnRequestId", "OccurredAt")
                        .HasDatabaseName("IX_returns_state_transitions_request_occurred");

                    b.HasIndex("ReturnRequestId", "Machine", "Trigger", "Reason")
                        .IsUnique()
                        .HasDatabaseName("IX_returns_state_transitions_admin_dedup")
                        .HasFilter("\"Machine\" = 'return' AND \"Reason\" IS NOT NULL");

                    b.ToTable("return_state_transitions", "returns", t =>
                        {
                            t.HasCheckConstraint("CK_returns_state_transitions_machine_enum", "\"Machine\" IN ('return','refund','inspection')");
                        });
                });

            modelBuilder.Entity("BackendApi.Modules.Returns.Entities.ReturnsOutboxEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CommittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DispatchAttempts")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("DispatchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<string>("MarketCode")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<DateTimeOffset?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.HasKey("Id");

                    b.HasIndex("AggregateId");

                    b.HasIndex("CommittedAt")
                        .HasDatabaseName("IX_returns_outbox_pending")
                        .HasFilter("\"DispatchedAt\" IS NULL");

                    b.HasIndex("MarketCode", "CommittedAt")
                        .HasDatabaseName("IX_returns_outbox_pending_per_market")
                        .HasFilter("\"DispatchedAt\" IS NULL");

                    b.ToTable("returns_outbox", "returns");
                });

            modelBuilder.Entity("BackendApi.Modules.Returns.Entities.Inspection", b =>
                {
                    b.HasOne("BackendApi.Modules.Returns.Entities.ReturnRequest", "ReturnRequest")
                        .WithMany("Inspections")
                        .HasForeignKey("ReturnRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReturnRequest");
                });

            modelBuilder.Entity("BackendApi.Modules.Returns.Entities.InspectionLine", b =>
                {
                    b.HasOne("BackendApi.Modules.Returns.Entities.Inspection", "Inspection")
                        .WithMany("Lines")
                        .HasForeignKey("InspectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendApi.Modules.Returns.Entities.ReturnLine", null)
                        .WithMany()
                        .HasForeignKey("ReturnLineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_inspection_lines_return_lines_ReturnLineId");

                    b.Navigation("Inspection");
                });

            modelBuilder.Entity("BackendApi.Modules.Returns.Entities.Refund", b =>
                {
                    b.HasOne("BackendApi.Modules.Returns.Entities.ReturnRequest", "ReturnRequest")
                        .WithMany("Refunds")
                        .HasForeignKey("ReturnRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReturnRequest");
                });

            modelBuilder.Entity("BackendApi.Modules.Returns.Entities.RefundLine", b =>
                {
                    b.HasOne("BackendApi.Modules.Returns.Entities.Refund", "Refund")
                        .WithMany("Lines")
                        .HasForeignKey("RefundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendApi.Modules.Returns.Entities.ReturnLine", null)
                        .WithMany()
                        .HasForeignKey("ReturnLineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_refund_lines_return_lines_ReturnLineId");

                    b.Navigation("Refund");
                });

            modelBuilder.Entity("BackendApi.Modules.Returns.Entities.ReturnLine", b =>
                {
                    b.HasOne("BackendApi.Modules.Returns.Entities.ReturnRequest", "ReturnRequest")
                        .WithMany("Lines")
                        .HasForeignKey("ReturnRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReturnRequest");
                });

            modelBuilder.Entity("BackendApi.Modules.Returns.Entities.ReturnPhoto", b =>
                {
                    b.HasOne("BackendApi.Modules.Returns.Entities.ReturnRequest", "ReturnRequest")
                        .WithMany("Photos")
                        .HasForeignKey("ReturnRequestId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ReturnRequest");
                });

            modelBuilder.Entity("BackendApi.Modules.Returns.Entities.ReturnStateTransition", b =>
                {
                    b.HasOne("BackendApi.Modules.Returns.Entities.ReturnRequest", null)
                        .WithMany("Transitions")
                        .HasForeignKey("ReturnRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BackendApi.Modules.Returns.Entities.Inspection", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("BackendApi.Modules.Returns.Entities.Refund", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("BackendApi.Modules.Returns.Entities.ReturnRequest", b =>
                {
                    b.Navigation("Inspections");

                    b.Navigation("Lines");

                    b.Navigation("Photos");

                    b.Navigation("Refunds");

                    b.Navigation("Transitions");
                });
#pragma warning restore 612, 618
        }
    }
}
