// <auto-generated />
using System;
using BackendApi.Modules.Verification.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BackendApi.Modules.Verification.Persistence.Migrations
{
    [DbContext(typeof(VerificationDbContext))]
    [Migration("20260429112711_VerificationInit")]
    partial class VerificationInit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("verification")
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BackendApi.Modules.Verification.Entities.Verification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DecidedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DecidedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MarketCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Profession")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RegulatorIdentifier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RestrictionPolicySnapshotJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("RestrictionPolicySnapshot");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("integer");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("SupersededById")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SupersedesId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VoidReason")
                        .HasColumnType("text");

                    b.Property<uint>("Xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("IX_verifications_expires_at")
                        .HasFilter("\"State\" = 'approved'");

                    b.HasIndex("SupersededById");

                    b.HasIndex("SupersedesId")
                        .HasDatabaseName("IX_verifications_supersedes")
                        .HasFilter("\"SupersedesId\" IS NOT NULL");

                    b.HasIndex("MarketCode", "SchemaVersion");

                    b.HasIndex("CustomerId", "State", "MarketCode")
                        .HasDatabaseName("IX_verifications_customer_state_market");

                    b.HasIndex("State", "MarketCode", "SubmittedAt")
                        .HasDatabaseName("IX_verifications_state_market_submitted")
                        .HasFilter("\"State\" IN ('submitted','in-review','info-requested')");

                    b.ToTable("verifications", "verification", t =>
                        {
                            t.HasCheckConstraint("CK_verifications_market_code_enum", "\"MarketCode\" IN ('eg','ksa')");

                            t.HasCheckConstraint("CK_verifications_state_enum", "\"State\" IN ('submitted','in-review','info-requested','approved','rejected','expired','revoked','superseded','void')");
                        });
                });

            modelBuilder.Entity("BackendApi.Modules.Verification.Entities.VerificationDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MarketCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("PurgeAfter")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("PurgedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ScanStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("pending");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("StorageKey")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VerificationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PurgeAfter")
                        .HasDatabaseName("IX_verification_documents_purge_after")
                        .HasFilter("\"PurgedAt\" IS NULL AND \"PurgeAfter\" IS NOT NULL");

                    b.HasIndex("VerificationId")
                        .HasDatabaseName("IX_verification_documents_verification");

                    b.HasIndex("MarketCode", "VerificationId")
                        .HasDatabaseName("IX_verification_documents_market_verification");

                    b.ToTable("verification_documents", "verification", t =>
                        {
                            t.HasCheckConstraint("CK_verification_documents_content_type_allowlist", "\"ContentType\" IN ('application/pdf','image/jpeg','image/png','image/heic')");

                            t.HasCheckConstraint("CK_verification_documents_market_code_enum", "\"MarketCode\" IN ('eg','ksa')");

                            t.HasCheckConstraint("CK_verification_documents_scan_status_enum", "\"ScanStatus\" IN ('pending','clean','infected','error')");

                            t.HasCheckConstraint("CK_verification_documents_size_bytes_limit", "\"SizeBytes\" > 0 AND \"SizeBytes\" <= 10485760");
                        });
                });

            modelBuilder.Entity("BackendApi.Modules.Verification.Entities.VerificationEligibilityCache", b =>
                {
                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("MarketCode")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ComputedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EligibilityClass")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProfessionsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("Professions")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<string>("ReasonCode")
                        .HasColumnType("text");

                    b.HasKey("CustomerId", "MarketCode");

                    b.HasIndex("MarketCode", "EligibilityClass")
                        .HasDatabaseName("IX_verification_eligibility_cache_market_class");

                    b.ToTable("verification_eligibility_cache", "verification", t =>
                        {
                            t.HasCheckConstraint("CK_verification_eligibility_cache_class_enum", "\"EligibilityClass\" IN ('eligible','ineligible','unrestricted_only')");

                            t.HasCheckConstraint("CK_verification_eligibility_cache_market_code_enum", "\"MarketCode\" IN ('eg','ksa')");
                        });
                });

            modelBuilder.Entity("BackendApi.Modules.Verification.Entities.VerificationMarketSchema", b =>
                {
                    b.Property<string>("MarketCode")
                        .HasColumnType("text");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.Property<string>("AllowedDocumentTypesJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("AllowedDocumentTypes");

                    b.Property<int>("CooldownDays")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("EffectiveTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ExpiryDays")
                        .HasColumnType("integer");

                    b.Property<string>("HolidaysListJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("HolidaysList");

                    b.Property<string>("ReminderWindowsDaysJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("ReminderWindowsDays");

                    b.Property<string>("RequiredFieldsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("RequiredFields");

                    b.Property<int>("RetentionMonths")
                        .HasColumnType("integer");

                    b.Property<int>("SlaDecisionBusinessDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(2);

                    b.Property<int>("SlaWarningBusinessDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.HasKey("MarketCode", "Version");

                    b.HasIndex("MarketCode")
                        .IsUnique()
                        .HasDatabaseName("UX_verification_market_schemas_active_per_market")
                        .HasFilter("\"EffectiveTo\" IS NULL");

                    b.ToTable("verification_market_schemas", "verification", t =>
                        {
                            t.HasCheckConstraint("CK_verification_market_schemas_cooldown_non_negative", "\"CooldownDays\" >= 0");

                            t.HasCheckConstraint("CK_verification_market_schemas_expiry_positive", "\"ExpiryDays\" > 0");

                            t.HasCheckConstraint("CK_verification_market_schemas_market_code_enum", "\"MarketCode\" IN ('eg','ksa')");

                            t.HasCheckConstraint("CK_verification_market_schemas_retention_non_negative", "\"RetentionMonths\" >= 0");

                            t.HasCheckConstraint("CK_verification_market_schemas_sla_warning_le_decision", "\"SlaWarningBusinessDays\" <= \"SlaDecisionBusinessDays\"");
                        });
                });

            modelBuilder.Entity("BackendApi.Modules.Verification.Entities.VerificationReminder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("EmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MarketCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SkipReason")
                        .HasColumnType("text");

                    b.Property<bool>("Skipped")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid>("VerificationId")
                        .HasColumnType("uuid");

                    b.Property<int>("WindowDays")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MarketCode", "VerificationId")
                        .HasDatabaseName("IX_verification_reminders_market_verification");

                    b.HasIndex("VerificationId", "WindowDays")
                        .IsUnique()
                        .HasDatabaseName("UX_verification_reminders_verification_window");

                    b.ToTable("verification_reminders", "verification", t =>
                        {
                            t.HasCheckConstraint("CK_verification_reminders_market_code_enum", "\"MarketCode\" IN ('eg','ksa')");

                            t.HasCheckConstraint("CK_verification_reminders_skip_reason_when_skipped", "\"Skipped\" = false OR (\"Skipped\" = true AND \"SkipReason\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_verification_reminders_window_positive", "\"WindowDays\" > 0");
                        });
                });

            modelBuilder.Entity("BackendApi.Modules.Verification.Entities.VerificationStateTransition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uuid");

                    b.Property<string>("ActorKind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MarketCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("Metadata")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("NewState")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PriorState")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("VerificationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MarketCode", "OccurredAt")
                        .HasDatabaseName("IX_verification_state_transitions_market_occurred");

                    b.HasIndex("VerificationId", "OccurredAt")
                        .HasDatabaseName("IX_verification_state_transitions_verification_occurred");

                    b.ToTable("verification_state_transitions", "verification", t =>
                        {
                            t.HasCheckConstraint("CK_verification_state_transitions_actor_id_by_kind", "(\"ActorKind\" = 'system' AND \"ActorId\" IS NULL) OR (\"ActorKind\" IN ('customer','reviewer') AND \"ActorId\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_verification_state_transitions_actor_kind_enum", "\"ActorKind\" IN ('customer','reviewer','system')");

                            t.HasCheckConstraint("CK_verification_state_transitions_market_code_enum", "\"MarketCode\" IN ('eg','ksa')");

                            t.HasCheckConstraint("CK_verification_state_transitions_new_state_enum", "\"NewState\" IN ('submitted','in-review','info-requested','approved','rejected','expired','revoked','superseded','void')");

                            t.HasCheckConstraint("CK_verification_state_transitions_prior_state_enum", "\"PriorState\" IN ('__none__','submitted','in-review','info-requested','approved','rejected','expired','revoked','superseded','void')");
                        });
                });

            modelBuilder.Entity("BackendApi.Modules.Verification.Entities.Verification", b =>
                {
                    b.HasOne("BackendApi.Modules.Verification.Entities.Verification", null)
                        .WithMany()
                        .HasForeignKey("SupersededById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BackendApi.Modules.Verification.Entities.Verification", null)
                        .WithMany()
                        .HasForeignKey("SupersedesId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BackendApi.Modules.Verification.Entities.VerificationMarketSchema", null)
                        .WithMany()
                        .HasForeignKey("MarketCode", "SchemaVersion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BackendApi.Modules.Verification.Entities.VerificationDocument", b =>
                {
                    b.HasOne("BackendApi.Modules.Verification.Entities.Verification", null)
                        .WithMany()
                        .HasForeignKey("VerificationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BackendApi.Modules.Verification.Entities.VerificationReminder", b =>
                {
                    b.HasOne("BackendApi.Modules.Verification.Entities.Verification", null)
                        .WithMany()
                        .HasForeignKey("VerificationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BackendApi.Modules.Verification.Entities.VerificationStateTransition", b =>
                {
                    b.HasOne("BackendApi.Modules.Verification.Entities.Verification", null)
                        .WithMany()
                        .HasForeignKey("VerificationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
