// <auto-generated />
using System;
using BackendApi.Modules.Catalog.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BackendApi.Modules.Catalog.Persistence.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    [Migration("20260423144646_Catalog_MediaClaimAndIdempotency")]
    partial class Catalog_MediaClaimAndIdempotency
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("catalog")
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BackendApi.Modules.Catalog.Entities.Brand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("LogoMediaId")
                        .HasColumnType("uuid");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("citext")
                        .HasDefaultValue("platform");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("VendorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasFilter("\"DeletedAt\" IS NULL");

                    b.ToTable("brands", "catalog");
                });

            modelBuilder.Entity("BackendApi.Modules.Catalog.Entities.BulkImportIdempotencyRecord", b =>
                {
                    b.Property<byte[]>("RowHash")
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.HasKey("RowHash");

                    b.ToTable("bulk_import_idempotency", "catalog");
                });

            modelBuilder.Entity("BackendApi.Modules.Catalog.Entities.CatalogOutboxEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CommittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DispatchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.HasKey("Id");

                    b.HasIndex("CommittedAt");

                    b.HasIndex("DispatchedAt")
                        .HasFilter("\"DispatchedAt\" IS NULL");

                    b.ToTable("catalog_outbox", "catalog");
                });

            modelBuilder.Entity("BackendApi.Modules.Catalog.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("citext")
                        .HasDefaultValue("platform");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("VendorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ParentId", "Slug")
                        .IsUnique()
                        .HasFilter("\"DeletedAt\" IS NULL");

                    b.HasIndex("OwnerId", "VendorId", "IsActive");

                    b.ToTable("categories", "catalog");
                });

            modelBuilder.Entity("BackendApi.Modules.Catalog.Entities.CategoryAttributeSchema", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("SchemaJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("CategoryId");

                    b.ToTable("category_attribute_schemas", "catalog");
                });

            modelBuilder.Entity("BackendApi.Modules.Catalog.Entities.CategoryClosure", b =>
                {
                    b.Property<Guid>("AncestorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DescendantId")
                        .HasColumnType("uuid");

                    b.Property<int>("Depth")
                        .HasColumnType("integer");

                    b.HasKey("AncestorId", "DescendantId");

                    b.HasIndex("DescendantId", "Depth");

                    b.ToTable("category_closure", "catalog");
                });

            modelBuilder.Entity("BackendApi.Modules.Catalog.Entities.Manufacturer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("LogoMediaId")
                        .HasColumnType("uuid");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("citext")
                        .HasDefaultValue("platform");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("VendorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasFilter("\"DeletedAt\" IS NULL");

                    b.ToTable("manufacturers", "catalog");
                });

            modelBuilder.Entity("BackendApi.Modules.Catalog.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AttributesJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("attributes")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("Barcode")
                        .HasColumnType("text");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByAccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DescriptionAr")
                        .HasColumnType("text");

                    b.Property<string>("DescriptionEn")
                        .HasColumnType("text");

                    b.Property<Guid?>("ManufacturerId")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<string[]>("MarketCodes")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("citext[]")
                        .HasDefaultValueSql("'{}'::citext[]");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("citext")
                        .HasDefaultValue("platform");

                    b.Property<long?>("PriceHintMinorUnits")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Restricted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.PrimitiveCollection<string[]>("RestrictionMarkets")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("citext[]")
                        .HasDefaultValueSql("'{}'::citext[]");

                    b.Property<string>("RestrictionReasonCode")
                        .HasColumnType("citext");

                    b.Property<string>("ShortDescriptionAr")
                        .HasColumnType("text");

                    b.Property<string>("ShortDescriptionEn")
                        .HasColumnType("text");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<string>("SlugAr")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<string>("SlugEn")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("citext")
                        .HasDefaultValue("draft");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("VendorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AttributesJson");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("AttributesJson"), "gin");

                    b.HasIndex("Barcode");

                    b.HasIndex("BrandId");

                    b.HasIndex("Sku")
                        .IsUnique()
                        .HasFilter("\"DeletedAt\" IS NULL");

                    b.HasIndex("Restricted", "RestrictionMarkets");

                    b.HasIndex("Status", "MarketCodes");

                    b.ToTable("products", "catalog");
                });

            modelBuilder.Entity("BackendApi.Modules.Catalog.Entities.ProductCategory", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.HasKey("ProductId", "CategoryId");

                    b.HasIndex("ProductId", "IsPrimary")
                        .IsUnique()
                        .HasFilter("\"IsPrimary\" = true");

                    b.ToTable("product_categories", "catalog");
                });

            modelBuilder.Entity("BackendApi.Modules.Catalog.Entities.ProductDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<byte[]>("ContentSha256")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DocType")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TitleAr")
                        .HasColumnType("text");

                    b.Property<string>("TitleEn")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProductId", "DocType", "Locale")
                        .IsUnique();

                    b.ToTable("product_documents", "catalog");
                });

            modelBuilder.Entity("BackendApi.Modules.Catalog.Entities.ProductMedia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AltAr")
                        .HasColumnType("text");

                    b.Property<string>("AltEn")
                        .HasColumnType("text");

                    b.Property<long>("Bytes")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("ContentSha256")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<int>("HeightPx")
                        .HasColumnType("integer");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("citext")
                        .HasDefaultValue("platform");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("VariantAttempts")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("VariantClaimedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VariantStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("citext")
                        .HasDefaultValue("pending");

                    b.Property<string>("VariantsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("variants")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<Guid?>("VendorId")
                        .HasColumnType("uuid");

                    b.Property<int>("WidthPx")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductId", "DisplayOrder");

                    b.HasIndex("ProductId", "IsPrimary")
                        .IsUnique()
                        .HasFilter("\"IsPrimary\" = true");

                    b.ToTable("product_media", "catalog");
                });

            modelBuilder.Entity("BackendApi.Modules.Catalog.Entities.ProductStateTransition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActorAccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("FromStatus")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.HasKey("Id");

                    b.HasIndex("ProductId", "OccurredAt");

                    b.ToTable("product_state_transitions", "catalog");
                });

            modelBuilder.Entity("BackendApi.Modules.Catalog.Entities.ScheduledPublish", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("PublishAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ScheduledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ScheduledByAccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("WorkerClaimedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("WorkerCompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ProductId");

                    b.HasIndex("PublishAt", "WorkerClaimedAt");

                    b.ToTable("scheduled_publishes", "catalog");
                });
#pragma warning restore 612, 618
        }
    }
}
