// <auto-generated />
using System;
using BackendApi.Modules.Cart.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BackendApi.Modules.Cart.Persistence.Migrations
{
    [DbContext(typeof(CartDbContext))]
    [Migration("20260424122016_Cart_MarketCodeOnChildren")]
    partial class Cart_MarketCodeOnChildren
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("cart")
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BackendApi.Modules.Cart.Entities.Cart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ArchivedReason")
                        .HasColumnType("citext");

                    b.Property<byte[]>("CartTokenHash")
                        .HasColumnType("bytea");

                    b.Property<string>("CouponCode")
                        .HasColumnType("citext");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LastTouchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MarketCode")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("citext")
                        .HasDefaultValue("platform");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("VendorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CartTokenHash")
                        .IsUnique()
                        .HasDatabaseName("IX_carts_token_hash_active")
                        .HasFilter("\"Status\" = 'active' AND \"CartTokenHash\" IS NOT NULL");

                    b.HasIndex("LastTouchedAt");

                    b.HasIndex("MarketCode");

                    b.HasIndex("Status");

                    b.HasIndex("AccountId", "MarketCode")
                        .IsUnique()
                        .HasDatabaseName("IX_carts_account_market_active")
                        .HasFilter("\"Status\" = 'active' AND \"AccountId\" IS NOT NULL");

                    b.ToTable("carts", "cart", t =>
                        {
                            t.HasCheckConstraint("CK_carts_identity_present", "\"AccountId\" IS NOT NULL OR \"CartTokenHash\" IS NOT NULL");

                            t.HasCheckConstraint("CK_carts_status_enum", "\"Status\" IN ('active','archived','merged','purged')");
                        });
                });

            modelBuilder.Entity("BackendApi.Modules.Cart.Entities.CartAbandonedEmission", b =>
                {
                    b.Property<Guid>("CartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("LastEmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MarketCode")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.HasKey("CartId");

                    b.HasIndex("LastEmittedAt");

                    b.HasIndex("MarketCode");

                    b.ToTable("cart_abandoned_emissions", "cart");
                });

            modelBuilder.Entity("BackendApi.Modules.Cart.Entities.CartB2BMetadata", b =>
                {
                    b.Property<Guid>("CartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("MarketCode")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("PoNumber")
                        .HasColumnType("text");

                    b.Property<string>("Reference")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("RequestedDeliveryFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("RequestedDeliveryTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CartId");

                    b.HasIndex("MarketCode");

                    b.ToTable("cart_b2b_metadata", "cart");
                });

            modelBuilder.Entity("BackendApi.Modules.Cart.Entities.CartLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CartId")
                        .HasColumnType("uuid");

                    b.Property<string>("MarketCode")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("Qty")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ReservationId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Restricted")
                        .HasColumnType("boolean");

                    b.Property<string>("RestrictionReasonCode")
                        .HasColumnType("citext");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<bool>("StockChanged")
                        .HasColumnType("boolean");

                    b.Property<bool>("Unavailable")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("MarketCode");

                    b.HasIndex("CartId", "ProductId")
                        .IsUnique();

                    b.ToTable("cart_lines", "cart", t =>
                        {
                            t.HasCheckConstraint("CK_cart_lines_qty_positive", "\"Qty\" >= 1");
                        });
                });

            modelBuilder.Entity("BackendApi.Modules.Cart.Entities.CartSavedItem", b =>
                {
                    b.Property<Guid>("CartId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("MarketCode")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<int>("Qty")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<DateTimeOffset>("SavedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CartId", "ProductId");

                    b.HasIndex("MarketCode");

                    b.ToTable("cart_saved_items", "cart", t =>
                        {
                            t.HasCheckConstraint("CK_cart_saved_items_qty_positive", "\"Qty\" >= 1");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
