// <auto-generated />
using System;
using BackendApi.Modules.Orders.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BackendApi.Modules.Orders.Persistence.Migrations
{
    [DbContext(typeof(OrdersDbContext))]
    [Migration("20260425142629_Orders_Initial")]
    partial class Orders_Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("orders")
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BackendApi.Modules.Orders.Entities.CancellationPolicyRow", b =>
                {
                    b.Property<string>("MarketCode")
                        .HasColumnType("citext");

                    b.Property<bool>("AuthorizedCancelAllowed")
                        .HasColumnType("boolean");

                    b.Property<int>("CapturedCancelHours")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByAccountId")
                        .HasColumnType("uuid");

                    b.HasKey("MarketCode");

                    b.ToTable("cancellation_policies", "orders", t =>
                        {
                            t.HasCheckConstraint("CK_orders_cancellation_policies_hours_non_negative", "\"CapturedCancelHours\" >= 0");
                        });
                });

            modelBuilder.Entity("BackendApi.Modules.Orders.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("B2bNotes")
                        .HasColumnType("text");

                    b.Property<string>("B2bPoNumber")
                        .HasColumnType("text");

                    b.Property<string>("B2bReference")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("B2bRequestedDeliveryFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("B2bRequestedDeliveryTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BillingAddressJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CheckoutSessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("CouponCode")
                        .HasColumnType("citext");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<DateTimeOffset?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("DiscountMinor")
                        .HasColumnType("bigint");

                    b.Property<string>("FulfillmentState")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("citext")
                        .HasDefaultValue("not_started");

                    b.Property<long>("GrandTotalMinor")
                        .HasColumnType("bigint");

                    b.Property<string>("MarketCode")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OrderState")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("citext")
                        .HasDefaultValue("placed");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("citext")
                        .HasDefaultValue("platform");

                    b.Property<string>("PaymentProviderId")
                        .HasColumnType("citext");

                    b.Property<string>("PaymentProviderTxnId")
                        .HasColumnType("text");

                    b.Property<string>("PaymentState")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("citext")
                        .HasDefaultValue("authorized");

                    b.Property<DateTimeOffset>("PlacedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PriceExplanationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("QuotationId")
                        .HasColumnType("uuid");

                    b.Property<string>("RefundState")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("citext")
                        .HasDefaultValue("none");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("ShippingAddressJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<long>("ShippingMinor")
                        .HasColumnType("bigint");

                    b.Property<long>("SubtotalMinor")
                        .HasColumnType("bigint");

                    b.Property<long>("TaxMinor")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("VendorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CheckoutSessionId")
                        .HasDatabaseName("IX_orders_orders_checkout_session");

                    b.HasIndex("FulfillmentState")
                        .HasDatabaseName("IX_orders_orders_fulfillment_state");

                    b.HasIndex("OrderNumber")
                        .IsUnique();

                    b.HasIndex("PaymentState")
                        .HasDatabaseName("IX_orders_orders_payment_state");

                    b.HasIndex("AccountId", "PlacedAt")
                        .HasDatabaseName("IX_orders_orders_account_placed");

                    b.HasIndex("MarketCode", "PlacedAt")
                        .HasDatabaseName("IX_orders_orders_market_placed");

                    b.ToTable("orders", "orders", t =>
                        {
                            t.HasCheckConstraint("CK_orders_orders_fulfillment_state_enum", "\"FulfillmentState\" IN ('not_started','awaiting_stock','picking','packed','handed_to_carrier','delivered','cancelled')");

                            t.HasCheckConstraint("CK_orders_orders_grand_total_non_negative", "\"GrandTotalMinor\" >= 0");

                            t.HasCheckConstraint("CK_orders_orders_order_state_enum", "\"OrderState\" IN ('placed','cancellation_pending','cancelled')");

                            t.HasCheckConstraint("CK_orders_orders_payment_state_enum", "\"PaymentState\" IN ('authorized','captured','pending_cod','pending_bank_transfer','failed','voided','refunded','partially_refunded')");

                            t.HasCheckConstraint("CK_orders_orders_refund_state_enum", "\"RefundState\" IN ('none','requested','partial','full')");
                        });
                });

            modelBuilder.Entity("BackendApi.Modules.Orders.Entities.OrderLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AttributesJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<int>("CancelledQty")
                        .HasColumnType("integer");

                    b.Property<long>("LineDiscountMinor")
                        .HasColumnType("bigint");

                    b.Property<long>("LineTaxMinor")
                        .HasColumnType("bigint");

                    b.Property<long>("LineTotalMinor")
                        .HasColumnType("bigint");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("Qty")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ReservationId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Restricted")
                        .HasColumnType("boolean");

                    b.Property<int>("ReturnedQty")
                        .HasColumnType("integer");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<long>("UnitPriceMinor")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("order_lines", "orders", t =>
                        {
                            t.HasCheckConstraint("CK_orders_order_lines_cancelled_qty_bounds", "\"CancelledQty\" >= 0 AND \"CancelledQty\" <= \"Qty\"");

                            t.HasCheckConstraint("CK_orders_order_lines_qty_positive", "\"Qty\" > 0");

                            t.HasCheckConstraint("CK_orders_order_lines_returned_qty_bounds", "\"ReturnedQty\" >= 0 AND (\"ReturnedQty\" + \"CancelledQty\") <= \"Qty\"");
                        });
                });

            modelBuilder.Entity("BackendApi.Modules.Orders.Entities.OrderStateTransition", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid?>("ActorAccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContextJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("FromState")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<string>("Machine")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<string>("ToState")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.HasKey("Id");

                    b.HasIndex("OrderId", "OccurredAt")
                        .HasDatabaseName("IX_orders_state_transitions_order_occurred");

                    b.ToTable("order_state_transitions", "orders", t =>
                        {
                            t.HasCheckConstraint("CK_orders_state_transitions_machine_enum", "\"Machine\" IN ('order','payment','fulfillment','refund')");
                        });
                });

            modelBuilder.Entity("BackendApi.Modules.Orders.Entities.OrdersOutboxEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CommittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DispatchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.HasKey("Id");

                    b.HasIndex("AggregateId");

                    b.HasIndex("CommittedAt")
                        .HasDatabaseName("IX_orders_outbox_pending")
                        .HasFilter("\"DispatchedAt\" IS NULL");

                    b.ToTable("orders_outbox", "orders");
                });

            modelBuilder.Entity("BackendApi.Modules.Orders.Entities.Quotation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ConvertedOrderId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByAccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("MarketCode")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<Guid>("PriceExplanationId")
                        .HasColumnType("uuid");

                    b.Property<string>("QuoteNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("citext")
                        .HasDefaultValue("draft");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ValidUntil")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("QuoteNumber")
                        .IsUnique();

                    b.HasIndex("ValidUntil");

                    b.HasIndex("AccountId", "Status");

                    b.ToTable("quotations", "orders", t =>
                        {
                            t.HasCheckConstraint("CK_orders_quotations_status_enum", "\"Status\" IN ('draft','active','accepted','rejected','expired','converted')");
                        });
                });

            modelBuilder.Entity("BackendApi.Modules.Orders.Entities.QuotationLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AttributesJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<long>("LineDiscountMinor")
                        .HasColumnType("bigint");

                    b.Property<long>("LineTaxMinor")
                        .HasColumnType("bigint");

                    b.Property<long>("LineTotalMinor")
                        .HasColumnType("bigint");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("Qty")
                        .HasColumnType("integer");

                    b.Property<Guid>("QuotationId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Restricted")
                        .HasColumnType("boolean");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<long>("UnitPriceMinor")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("QuotationId");

                    b.ToTable("quotation_lines", "orders", t =>
                        {
                            t.HasCheckConstraint("CK_orders_quotation_lines_qty_positive", "\"Qty\" > 0");
                        });
                });

            modelBuilder.Entity("BackendApi.Modules.Orders.Entities.Shipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CarrierLabelUrl")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("EtaFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("EtaTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("HandedToCarrierAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MethodCode")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<string>("State")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("citext")
                        .HasDefaultValue("created");

                    b.Property<string>("TrackingNumber")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProviderId", "TrackingNumber");

                    b.ToTable("shipments", "orders", t =>
                        {
                            t.HasCheckConstraint("CK_orders_shipments_state_enum", "\"State\" IN ('created','handed_to_carrier','in_transit','out_for_delivery','delivered','returned','failed')");
                        });
                });

            modelBuilder.Entity("BackendApi.Modules.Orders.Entities.ShipmentLine", b =>
                {
                    b.Property<Guid>("ShipmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrderLineId")
                        .HasColumnType("uuid");

                    b.Property<int>("Qty")
                        .HasColumnType("integer");

                    b.HasKey("ShipmentId", "OrderLineId");

                    b.HasIndex("OrderLineId");

                    b.ToTable("shipment_lines", "orders", t =>
                        {
                            t.HasCheckConstraint("CK_orders_shipment_lines_qty_positive", "\"Qty\" > 0");
                        });
                });

            modelBuilder.Entity("BackendApi.Modules.Orders.Entities.OrderLine", b =>
                {
                    b.HasOne("BackendApi.Modules.Orders.Entities.Order", "Order")
                        .WithMany("Lines")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("BackendApi.Modules.Orders.Entities.QuotationLine", b =>
                {
                    b.HasOne("BackendApi.Modules.Orders.Entities.Quotation", "Quotation")
                        .WithMany("Lines")
                        .HasForeignKey("QuotationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quotation");
                });

            modelBuilder.Entity("BackendApi.Modules.Orders.Entities.Shipment", b =>
                {
                    b.HasOne("BackendApi.Modules.Orders.Entities.Order", "Order")
                        .WithMany("Shipments")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("BackendApi.Modules.Orders.Entities.ShipmentLine", b =>
                {
                    b.HasOne("BackendApi.Modules.Orders.Entities.OrderLine", "OrderLine")
                        .WithMany()
                        .HasForeignKey("OrderLineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BackendApi.Modules.Orders.Entities.Shipment", "Shipment")
                        .WithMany("Lines")
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderLine");

                    b.Navigation("Shipment");
                });

            modelBuilder.Entity("BackendApi.Modules.Orders.Entities.Order", b =>
                {
                    b.Navigation("Lines");

                    b.Navigation("Shipments");
                });

            modelBuilder.Entity("BackendApi.Modules.Orders.Entities.Quotation", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("BackendApi.Modules.Orders.Entities.Shipment", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
