// <auto-generated />
using System;
using BackendApi.Modules.Payments.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BackendApi.Modules.Payments.Persistence.Migrations
{
    [DbContext(typeof(PaymentsDbContext))]
    [Migration("20260517073918_CreatePaymentsSchema")]
    partial class CreatePaymentsSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("payments")
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BackendApi.Modules.Payments.Domain.BankTransferReference", b =>
                {
                    b.Property<Guid>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("MatchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MatchedBankStatementEntryJson")
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("MatchedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PaymentId");

                    b.HasIndex("Reference")
                        .IsUnique()
                        .HasDatabaseName("UX_bank_transfer_reference")
                        .HasFilter("\"DeletedAt\" IS NULL");

                    b.ToTable("bank_transfer_references", "payments", t =>
                        {
                            t.HasCheckConstraint("CK_bank_transfer_reference_format", "\"Reference\" ~ '^(SA|EG)-[0-9a-f]{8}-[A-Z0-9]{4}$'");
                        });
                });

            modelBuilder.Entity("BackendApi.Modules.Payments.Domain.Chargeback", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(12,2)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PaymentId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProviderChargebackId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReasonCode")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ResolutionNotes")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ResolvedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PaymentId")
                        .HasDatabaseName("IX_chargebacks_payment");

                    b.HasIndex("ProviderChargebackId")
                        .IsUnique()
                        .HasDatabaseName("UX_chargebacks_provider_id")
                        .HasFilter("\"DeletedAt\" IS NULL");

                    b.ToTable("chargebacks", "payments", t =>
                        {
                            t.HasCheckConstraint("CK_chargebacks_amount_positive", "\"Amount\" > 0");

                            t.HasCheckConstraint("CK_chargebacks_status", "\"Status\" IN ('received','disputed','lost','won','accepted')");
                        });
                });

            modelBuilder.Entity("BackendApi.Modules.Payments.Domain.CodCollectionLog", b =>
                {
                    b.Property<Guid>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("AmountCollected")
                        .HasColumnType("numeric(12,2)");

                    b.Property<DateTimeOffset?>("CollectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CourierUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("OperatorConfirmedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("OperatorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PaymentId");

                    b.ToTable("cod_collection_log", "payments", t =>
                        {
                            t.HasCheckConstraint("CK_cod_collection_log_amount_nonneg", "\"AmountCollected\" IS NULL OR \"AmountCollected\" >= 0");

                            t.HasCheckConstraint("CK_cod_collection_log_outcome", "\"Outcome\" IN ('collected','refused','address_not_found')");
                        });
                });

            modelBuilder.Entity("BackendApi.Modules.Payments.Domain.IdempotencyKey", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PaymentId")
                        .HasColumnType("uuid");

                    b.HasKey("Key");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("IX_idempotency_keys_expires");

                    b.HasIndex("PaymentId")
                        .HasDatabaseName("IX_idempotency_keys_payment");

                    b.ToTable("idempotency_keys", "payments");
                });

            modelBuilder.Entity("BackendApi.Modules.Payments.Domain.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(12,2)");

                    b.Property<Guid>("AttemptId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("AuthorizedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("CapturedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ExpiredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExpiredReason")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("FailedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FailedReason")
                        .HasColumnType("text");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MarketCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProviderId")
                        .HasColumnType("text");

                    b.Property<string>("ProviderMessageId")
                        .HasColumnType("text");

                    b.Property<string>("RecipientPayloadRedactedJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("Xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("IX_payments_customer");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("UX_payments_idempotency_key_active")
                        .HasFilter("\"DeletedAt\" IS NULL");

                    b.HasIndex("State")
                        .HasDatabaseName("IX_payments_active_state")
                        .HasFilter("\"State\" IN ('pending_authorization','pending_external_redirect','pending_collection_on_delivery','pending_bank_transfer','authorized','capture_failed')");

                    b.HasIndex("OrderId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_payments_order_created_desc");

                    b.HasIndex("ProviderId", "ProviderMessageId")
                        .HasDatabaseName("IX_payments_provider_message");

                    b.ToTable("payments", "payments", t =>
                        {
                            t.HasCheckConstraint("CK_payments_amount_positive", "\"Amount\" > 0");

                            t.HasCheckConstraint("CK_payments_currency", "\"Currency\" IN ('SAR','EGP')");

                            t.HasCheckConstraint("CK_payments_currency_matches_market", "(\"MarketCode\" = 'sa' AND \"Currency\" = 'SAR') OR (\"MarketCode\" = 'eg' AND \"Currency\" = 'EGP')");

                            t.HasCheckConstraint("CK_payments_market_code", "\"MarketCode\" IN ('sa','eg')");

                            t.HasCheckConstraint("CK_payments_method", "\"Method\" IN ('card','apple_pay','mada','stc_pay','meeza','bnpl_tabby','bnpl_tamara','bnpl_valu','cod','bank_transfer')");

                            t.HasCheckConstraint("CK_payments_state", "\"State\" IN ('pending_authorization','pending_external_redirect','pending_collection_on_delivery','pending_bank_transfer','authorized','capture_failed','captured','failed','expired','refunded','partially_refunded','chargeback_received')");
                        });
                });

            modelBuilder.Entity("BackendApi.Modules.Payments.Domain.PaymentMethodMarketConfig", b =>
                {
                    b.Property<string>("MarketCode")
                        .HasColumnType("text");

                    b.Property<string>("Method")
                        .HasColumnType("text");

                    b.Property<string>("EligibilityJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<decimal?>("MaxCartTotal")
                        .HasColumnType("numeric(12,2)");

                    b.Property<decimal?>("MinCartTotal")
                        .HasColumnType("numeric(12,2)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("MarketCode", "Method");

                    b.ToTable("payment_methods_market_config", "payments", t =>
                        {
                            t.HasCheckConstraint("CK_payment_methods_cart_total_bounds", "\"MinCartTotal\" IS NULL OR \"MaxCartTotal\" IS NULL OR \"MinCartTotal\" <= \"MaxCartTotal\"");

                            t.HasCheckConstraint("CK_payment_methods_market", "\"MarketCode\" IN ('sa','eg')");
                        });
                });

            modelBuilder.Entity("BackendApi.Modules.Payments.Domain.PciScopeEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ChangeSummary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ChangedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventKind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("IX_pci_scope_events_created_desc");

                    b.ToTable("pci_scope_events", "payments", t =>
                        {
                            t.HasCheckConstraint("CK_pci_scope_events_kind", "\"EventKind\" IN ('kv_slot_added','kv_slot_removed','hosted_fields_domain_changed','provider_added','provider_removed')");
                        });
                });

            modelBuilder.Entity("BackendApi.Modules.Payments.Domain.ProviderRouting", b =>
                {
                    b.Property<string>("MarketCode")
                        .HasColumnType("text");

                    b.Property<string>("Method")
                        .HasColumnType("text");

                    b.Property<bool>("AutoFailoverEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("BackupProviderId")
                        .HasColumnType("text");

                    b.Property<int>("FailoverThresholdPct")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(50);

                    b.Property<int>("FailoverWindowMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(5);

                    b.Property<string>("PrimaryProviderId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("MarketCode", "Method");

                    b.ToTable("provider_routing", "payments", t =>
                        {
                            t.HasCheckConstraint("CK_provider_routing_market", "\"MarketCode\" IN ('sa','eg')");

                            t.HasCheckConstraint("CK_provider_routing_primary_not_backup", "\"BackupProviderId\" IS NULL OR \"PrimaryProviderId\" <> \"BackupProviderId\"");

                            t.HasCheckConstraint("CK_provider_routing_threshold", "\"FailoverThresholdPct\" BETWEEN 1 AND 100");

                            t.HasCheckConstraint("CK_provider_routing_window", "\"FailoverWindowMinutes\" > 0");
                        });
                });

            modelBuilder.Entity("BackendApi.Modules.Payments.Domain.ReconciliationException", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("InternalAmount")
                        .HasColumnType("numeric(12,2)");

                    b.Property<Guid?>("InternalPaymentId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("ProviderAmount")
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("ProviderId")
                        .HasColumnType("text");

                    b.Property<string>("ProviderLedgerRowJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Resolution")
                        .HasColumnType("text");

                    b.Property<string>("ResolutionNotes")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ResolvedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RunId")
                        .HasDatabaseName("IX_reconciliation_exceptions_run");

                    b.HasIndex("State", "CreatedAt")
                        .HasDatabaseName("IX_reconciliation_exceptions_state_created")
                        .HasFilter("\"DeletedAt\" IS NULL");

                    b.ToTable("reconciliation_exceptions", "payments", t =>
                        {
                            t.HasCheckConstraint("CK_reconciliation_exceptions_reason", "\"Reason\" IN ('orphan_provider_row','missing_on_provider','amount_mismatch','currency_mismatch')");

                            t.HasCheckConstraint("CK_reconciliation_exceptions_resolution", "\"Resolution\" IS NULL OR \"Resolution\" IN ('refund_issued','internal_correction','provider_correction_requested','accepted_loss')");

                            t.HasCheckConstraint("CK_reconciliation_exceptions_resolved_consistency", "(\"State\" = 'open' AND \"Resolution\" IS NULL AND \"ResolvedAt\" IS NULL AND \"ResolvedBy\" IS NULL) OR (\"State\" = 'resolved' AND \"Resolution\" IS NOT NULL AND \"ResolvedAt\" IS NOT NULL AND \"ResolvedBy\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_reconciliation_exceptions_state", "\"State\" IN ('open','resolved')");
                        });
                });

            modelBuilder.Entity("BackendApi.Modules.Payments.Domain.ReconciliationRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("DateRangeEnd")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DateRangeStart")
                        .HasColumnType("date");

                    b.Property<int>("ExceptionsCount")
                        .HasColumnType("integer");

                    b.Property<int>("InternalPaymentsCount")
                        .HasColumnType("integer");

                    b.Property<int>("MatchedCount")
                        .HasColumnType("integer");

                    b.Property<int>("ProviderLedgerRowsCount")
                        .HasColumnType("integer");

                    b.Property<string>("ProvidersProcessedJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("StartedAt")
                        .IsDescending()
                        .HasDatabaseName("IX_reconciliation_runs_started_desc");

                    b.ToTable("reconciliation_runs", "payments", t =>
                        {
                            t.HasCheckConstraint("CK_reconciliation_runs_date_range", "\"DateRangeStart\" <= \"DateRangeEnd\"");

                            t.HasCheckConstraint("CK_reconciliation_runs_status", "\"Status\" IN ('running','completed','failed')");
                        });
                });

            modelBuilder.Entity("BackendApi.Modules.Payments.Domain.Refund", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(12,2)");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("FailedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FailedReason")
                        .HasColumnType("text");

                    b.Property<Guid>("InitiatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PaymentId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProviderRefundId")
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PaymentId")
                        .HasDatabaseName("IX_refunds_payment");

                    b.HasIndex("PaymentId", "State")
                        .HasDatabaseName("IX_refunds_payment_state")
                        .HasFilter("\"DeletedAt\" IS NULL");

                    b.ToTable("refunds", "payments", t =>
                        {
                            t.HasCheckConstraint("CK_refunds_amount_positive", "\"Amount\" > 0");

                            t.HasCheckConstraint("CK_refunds_currency", "\"Currency\" IN ('SAR','EGP')");

                            t.HasCheckConstraint("CK_refunds_state", "\"State\" IN ('pending','completed','failed')");
                        });
                });

            modelBuilder.Entity("BackendApi.Modules.Payments.Domain.WebhookReceived", b =>
                {
                    b.Property<string>("ProviderId")
                        .HasColumnType("text");

                    b.Property<string>("ProviderMessageId")
                        .HasColumnType("text");

                    b.Property<string>("EventKind")
                        .HasColumnType("text");

                    b.Property<string>("BodyHash")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("SignatureValidated")
                        .HasColumnType("boolean");

                    b.HasKey("ProviderId", "ProviderMessageId", "EventKind");

                    b.HasIndex("ReceivedAt")
                        .HasDatabaseName("IX_webhooks_received_at");

                    b.ToTable("webhooks_received", "payments");
                });
#pragma warning restore 612, 618
        }
    }
}
