// <auto-generated />
using System;
using BackendApi.Modules.Support.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BackendApi.Modules.Support.Persistence.Migrations
{
    [DbContext(typeof(SupportDbContext))]
    partial class SupportDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("support")
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BackendApi.Modules.Support.Entities.SlaPolicy", b =>
                {
                    b.Property<string>("MarketCode")
                        .HasColumnType("text");

                    b.Property<string>("Priority")
                        .HasColumnType("text");

                    b.Property<int>("FirstResponseTargetMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("ResolutionTargetMinutes")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByActorId")
                        .HasColumnType("uuid");

                    b.HasKey("MarketCode", "Priority");

                    b.ToTable("sla_policies", "support", t =>
                        {
                            t.HasCheckConstraint("CK_sla_policies_market_code", "\"MarketCode\" IN ('SA','EG')");

                            t.HasCheckConstraint("CK_sla_policies_priority", "\"Priority\" IN ('low','normal','high','urgent')");

                            t.HasCheckConstraint("CK_sla_policies_resolution_gt_first", "\"ResolutionTargetMinutes\" > \"FirstResponseTargetMinutes\"");

                            t.HasCheckConstraint("CK_sla_policies_targets_positive", "\"FirstResponseTargetMinutes\" > 0 AND \"ResolutionTargetMinutes\" > 0");
                        });
                });

            modelBuilder.Entity("BackendApi.Modules.Support.Entities.SupportAgentAvailability", b =>
                {
                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid");

                    b.Property<string>("MarketCode")
                        .HasColumnType("text");

                    b.Property<bool>("IsOnCall")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastToggledAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LastToggledByActorId")
                        .HasColumnType("uuid");

                    b.HasKey("AgentId", "MarketCode");

                    b.ToTable("agent_availability", "support", t =>
                        {
                            t.HasCheckConstraint("CK_agent_availability_market_code", "\"MarketCode\" IN ('SA','EG')");
                        });
                });

            modelBuilder.Entity("BackendApi.Modules.Support.Entities.SupportMarketSchema", b =>
                {
                    b.Property<string>("MarketCode")
                        .HasColumnType("text");

                    b.PrimitiveCollection<string[]>("AllowedMimeTypes")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int>("AttachmentCumulativeMaxMb")
                        .HasColumnType("integer");

                    b.Property<int>("AttachmentMaxPerTicket")
                        .HasColumnType("integer");

                    b.Property<int>("AttachmentMaxSizeMb")
                        .HasColumnType("integer");

                    b.Property<bool>("AutoAssignmentEnabled")
                        .HasColumnType("boolean");

                    b.Property<int>("AutoCloseAfterResolvedDays")
                        .HasColumnType("integer");

                    b.Property<int>("MaxReopenCount")
                        .HasColumnType("integer");

                    b.Property<int>("ReopenWindowDays")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByActorId")
                        .HasColumnType("uuid");

                    b.HasKey("MarketCode");

                    b.ToTable("support_market_schemas", "support", t =>
                        {
                            t.HasCheckConstraint("CK_market_schemas_attachment_caps", "\"AttachmentMaxPerTicket\" > 0 AND \"AttachmentMaxSizeMb\" > 0 AND \"AttachmentCumulativeMaxMb\" > 0");

                            t.HasCheckConstraint("CK_market_schemas_auto_close", "\"AutoCloseAfterResolvedDays\" BETWEEN 0 AND 30");

                            t.HasCheckConstraint("CK_market_schemas_market_code", "\"MarketCode\" IN ('SA','EG')");

                            t.HasCheckConstraint("CK_market_schemas_max_reopen", "\"MaxReopenCount\" BETWEEN 1 AND 10");

                            t.HasCheckConstraint("CK_market_schemas_reopen_window", "\"ReopenWindowDays\" BETWEEN 0 AND 60");
                        });
                });

            modelBuilder.Entity("BackendApi.Modules.Support.Entities.SupportTicket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("AssignedAgentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("BreachAcknowledgedAtFirstResponse")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("BreachAcknowledgedAtResolution")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ClosedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("FirstResponseDueUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FirstResponseTargetMinutesSnapshot")
                        .HasColumnType("integer");

                    b.Property<Guid?>("LinkedEntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("LinkedEntityKind")
                        .HasColumnType("text");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MarketCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ReopenCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("ReopenedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ResolutionDueUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ResolutionTargetMinutesSnapshot")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("ResolvedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("VendorId")
                        .HasColumnType("uuid");

                    b.Property<uint>("Xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("VendorId")
                        .HasDatabaseName("IX_tickets_vendor")
                        .HasFilter("\"VendorId\" IS NOT NULL");

                    b.HasIndex("AssignedAgentId", "State")
                        .HasDatabaseName("IX_tickets_assigned_agent")
                        .HasFilter("\"State\" IN ('in_progress','waiting_customer')");

                    b.HasIndex("CompanyId", "State")
                        .HasDatabaseName("IX_tickets_company")
                        .HasFilter("\"CompanyId\" IS NOT NULL");

                    b.HasIndex("CustomerId", "CreatedAtUtc")
                        .HasDatabaseName("IX_tickets_customer");

                    b.HasIndex("LinkedEntityKind", "LinkedEntityId")
                        .HasDatabaseName("IX_tickets_linked_entity");

                    b.HasIndex("State", "FirstResponseDueUtc", "ResolutionDueUtc")
                        .HasDatabaseName("IX_tickets_breach_scan")
                        .HasFilter("\"State\" NOT IN ('closed')");

                    b.HasIndex("MarketCode", "State", "FirstResponseDueUtc", "CreatedAtUtc")
                        .HasDatabaseName("IX_tickets_queue");

                    b.ToTable("tickets", "support", t =>
                        {
                            t.HasCheckConstraint("CK_tickets_body_len", "char_length(\"Body\") BETWEEN 1 AND 8000");

                            t.HasCheckConstraint("CK_tickets_category", "\"Category\" IN ('order_issue','payment_issue','shipping_issue','product_defect','return_refund_request','quote_question','account_verification','general_question','review_dispute','verification_query','redaction_request')");

                            t.HasCheckConstraint("CK_tickets_linked_entity_kind", "\"LinkedEntityKind\" IS NULL OR \"LinkedEntityKind\" IN ('order','order_line','return_request','quote','review','verification')");

                            t.HasCheckConstraint("CK_tickets_linked_kind_consistency", "(\"LinkedEntityKind\" IS NULL AND \"LinkedEntityId\" IS NULL) OR (\"LinkedEntityKind\" IS NOT NULL AND \"LinkedEntityId\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_tickets_locale", "\"Locale\" IN ('ar','en')");

                            t.HasCheckConstraint("CK_tickets_market_code", "\"MarketCode\" IN ('SA','EG')");

                            t.HasCheckConstraint("CK_tickets_priority", "\"Priority\" IN ('low','normal','high','urgent')");

                            t.HasCheckConstraint("CK_tickets_reopen_count_nonneg", "\"ReopenCount\" >= 0");

                            t.HasCheckConstraint("CK_tickets_sla_targets_positive", "\"FirstResponseTargetMinutesSnapshot\" > 0 AND \"ResolutionTargetMinutesSnapshot\" > 0");

                            t.HasCheckConstraint("CK_tickets_state", "\"State\" IN ('open','in_progress','waiting_customer','resolved','closed')");

                            t.HasCheckConstraint("CK_tickets_subject_len", "char_length(\"Subject\") BETWEEN 1 AND 150");
                        });
                });

            modelBuilder.Entity("BackendApi.Modules.Support.Entities.TicketAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AssignedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("AssignedByActorId")
                        .HasColumnType("uuid");

                    b.Property<string>("AssignmentKind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("JustificationNote")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("SupersededAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SupersededReason")
                        .HasColumnType("text");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TicketId")
                        .IsUnique()
                        .HasDatabaseName("UX_ticket_assignments_active_per_ticket")
                        .HasFilter("\"SupersededAtUtc\" IS NULL");

                    b.HasIndex("TicketId", "AssignedAtUtc")
                        .HasDatabaseName("IX_ticket_assignments_ticket");

                    b.ToTable("ticket_assignments", "support", t =>
                        {
                            t.HasCheckConstraint("CK_ticket_assignments_kind", "\"AssignmentKind\" IN ('self_claim','auto_assignment','lead_reassignment','reclaim_after_offboard')");

                            t.HasCheckConstraint("CK_ticket_assignments_supersede_consistency", "(\"SupersededAtUtc\" IS NULL AND \"SupersededReason\" IS NULL) OR (\"SupersededAtUtc\" IS NOT NULL AND \"SupersededReason\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_ticket_assignments_superseded_reason", "\"SupersededReason\" IS NULL OR \"SupersededReason\" IN ('reassigned','reclaimed_offboard','reopened_back_to_queue')");
                        });
                });

            modelBuilder.Entity("BackendApi.Modules.Support.Entities.TicketAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OriginalFilename")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("RedactedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RedactedByRole")
                        .HasColumnType("text");

                    b.Property<string>("RedactionReasonNote")
                        .HasColumnType("text");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("State")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("active");

                    b.Property<string>("StorageObjectId")
                        .HasColumnType("text");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MessageId")
                        .HasDatabaseName("IX_ticket_attachments_message");

                    b.HasIndex("TicketId")
                        .HasDatabaseName("IX_ticket_attachments_ticket");

                    b.ToTable("ticket_attachments", "support", t =>
                        {
                            t.HasCheckConstraint("CK_ticket_attachments_redaction_consistency", "(\"State\" = 'active' AND \"StorageObjectId\" IS NOT NULL AND \"RedactedAtUtc\" IS NULL) OR (\"State\" = 'redacted' AND \"RedactedAtUtc\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_ticket_attachments_size_bytes", "\"SizeBytes\" >= 0");

                            t.HasCheckConstraint("CK_ticket_attachments_state", "\"State\" IN ('active','redacted')");
                        });
                });

            modelBuilder.Entity("BackendApi.Modules.Support.Entities.TicketLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedVia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IdempotencyKey")
                        .HasColumnType("text");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("LinkedEntityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TicketId")
                        .HasDatabaseName("IX_ticket_links_ticket");

                    b.HasIndex("Kind", "LinkedEntityId")
                        .HasDatabaseName("IX_ticket_links_lookup");

                    b.HasIndex("TicketId", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("UX_ticket_links_idempotency_key")
                        .HasFilter("\"IdempotencyKey\" IS NOT NULL");

                    b.ToTable("ticket_links", "support", t =>
                        {
                            t.HasCheckConstraint("CK_ticket_links_created_via", "\"CreatedVia\" IN ('submission','conversion','lead_link')");

                            t.HasCheckConstraint("CK_ticket_links_kind", "\"Kind\" IN ('order','order_line','return_request','quote','review','verification')");
                        });
                });

            modelBuilder.Entity("BackendApi.Modules.Support.Entities.TicketMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uuid");

                    b.Property<string>("ActorRole")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Body")
                        .HasColumnType("text");

                    b.Property<string>("BodyLocale")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("LeadIntervention")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("OriginatingRedactionRequestTicketId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("RedactedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RedactedByRole")
                        .HasColumnType("text");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TicketId", "CreatedAtUtc")
                        .HasDatabaseName("IX_ticket_messages_ticket");

                    b.HasIndex("TicketId", "Kind")
                        .HasDatabaseName("IX_ticket_messages_ticket_kind");

                    b.ToTable("ticket_messages", "support", t =>
                        {
                            t.HasCheckConstraint("CK_ticket_messages_body_len", "\"Body\" IS NULL OR char_length(\"Body\") BETWEEN 1 AND 8000");

                            t.HasCheckConstraint("CK_ticket_messages_body_locale", "\"BodyLocale\" IS NULL OR \"BodyLocale\" IN ('ar','en')");

                            t.HasCheckConstraint("CK_ticket_messages_kind", "\"Kind\" IN ('customer_reply','agent_reply','internal_note','system_event')");
                        });
                });

            modelBuilder.Entity("BackendApi.Modules.Support.Entities.TicketSlaBreachEvent", b =>
                {
                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid");

                    b.Property<string>("BreachKind")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("DetectedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EventEmitted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("SupersededByEventId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("TargetDueUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TicketId", "BreachKind", "DetectedAtUtc");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasDatabaseName("UX_breach_events_surrogate_id");

                    b.HasIndex("TicketId", "BreachKind")
                        .HasDatabaseName("IX_breach_events_ticket_kind");

                    b.ToTable("ticket_sla_breach_events", "support", t =>
                        {
                            t.HasCheckConstraint("CK_breach_events_kind", "\"BreachKind\" IN ('first_response','resolution')");
                        });
                });

            modelBuilder.Entity("BackendApi.Modules.Support.Entities.TicketAssignment", b =>
                {
                    b.HasOne("BackendApi.Modules.Support.Entities.SupportTicket", null)
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BackendApi.Modules.Support.Entities.TicketAttachment", b =>
                {
                    b.HasOne("BackendApi.Modules.Support.Entities.TicketMessage", null)
                        .WithMany()
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BackendApi.Modules.Support.Entities.TicketLink", b =>
                {
                    b.HasOne("BackendApi.Modules.Support.Entities.SupportTicket", null)
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BackendApi.Modules.Support.Entities.TicketMessage", b =>
                {
                    b.HasOne("BackendApi.Modules.Support.Entities.SupportTicket", null)
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BackendApi.Modules.Support.Entities.TicketSlaBreachEvent", b =>
                {
                    b.HasOne("BackendApi.Modules.Support.Entities.SupportTicket", null)
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
