// <auto-generated />
using System;
using BackendApi.Modules.Search.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BackendApi.Modules.Search.Persistence.Migrations
{
    [DbContext(typeof(SearchDbContext))]
    partial class SearchDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("search")
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BackendApi.Modules.Search.Entities.ReindexJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DocsExpected")
                        .HasColumnType("integer");

                    b.Property<int>("DocsWritten")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<string>("IndexName")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("StartedByAccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.HasKey("Id");

                    b.HasIndex("IndexName")
                        .IsUnique()
                        .HasFilter("\"Status\" IN ('pending','running')");

                    b.HasIndex("StartedAt");

                    b.HasIndex("IndexName", "Status");

                    b.ToTable("reindex_jobs", "search");
                });

            modelBuilder.Entity("BackendApi.Modules.Search.Entities.SearchIndexerCursor", b =>
                {
                    b.Property<string>("IndexName")
                        .HasColumnType("citext");

                    b.Property<int>("LagSecondsLastObserved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTimeOffset>("LastSuccessAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("OutboxLastIdApplied")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("IndexName");

                    b.HasIndex("UpdatedAt");

                    b.ToTable("search_indexer_cursor", "search");
                });
#pragma warning restore 612, 618
        }
    }
}
