// <auto-generated />
using System;
using BackendApi.Modules.B2B.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BackendApi.Modules.B2B.Persistence.Migrations
{
    [DbContext(typeof(B2BDbContext))]
    [Migration("20260503103643_B2BInit")]
    partial class B2BInit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("b2b")
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BackendApi.Modules.B2B.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("ApproverRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("approver_required");

                    b.Property<string>("BillingAddressJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("billing_address");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("InvoiceBillingEligible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("invoice_billing_eligible");

                    b.Property<string>("MarketCode")
                        .IsRequired()
                        .HasColumnType("citext")
                        .HasColumnName("market_code");

                    b.Property<string>("NameJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("name");

                    b.Property<bool>("PoRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("po_required");

                    b.Property<string>("PrimaryAddressJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("primary_address");

                    b.Property<string>("State")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("citext")
                        .HasDefaultValue("active")
                        .HasColumnName("state");

                    b.Property<string>("TaxId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("text")
                        .HasColumnName("tax_id");

                    b.Property<bool>("UniquePoRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("unique_po_required");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("XminRowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("State")
                        .HasDatabaseName("IX_companies_state")
                        .HasFilter("state::text <> 'closed'");

                    b.HasIndex("MarketCode", "TaxId")
                        .IsUnique()
                        .HasDatabaseName("UX_companies_market_tax_id");

                    b.ToTable("companies", "b2b", t =>
                        {
                            t.HasCheckConstraint("chk_companies_market", "market_code::text IN ('eg','ksa')");

                            t.HasCheckConstraint("chk_companies_state", "state::text IN ('active','pending-verification','suspended','closed')");
                        });
                });

            modelBuilder.Entity("BackendApi.Modules.B2B.Entities.CompanyBranch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AddressJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("address");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(64)
                        .HasColumnType("text")
                        .HasColumnName("contact_phone");

                    b.Property<string>("NameJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("IX_company_branches_company");

                    b.ToTable("company_branches", "b2b");
                });

            modelBuilder.Entity("BackendApi.Modules.B2B.Entities.CompanyInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("InvitedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("invited_by");

                    b.Property<string>("InvitedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("citext")
                        .HasColumnName("invited_email");

                    b.Property<DateTimeOffset>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<string>("State")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("citext")
                        .HasDefaultValue("pending")
                        .HasColumnName("state");

                    b.Property<string>("TargetRole")
                        .IsRequired()
                        .HasColumnType("citext")
                        .HasColumnName("target_role");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("UX_company_invitations_token");

                    b.HasIndex("State", "ExpiresAt")
                        .HasDatabaseName("IX_company_invitations_state_expires")
                        .HasFilter("state::text = 'pending'");

                    b.HasIndex("CompanyId", "InvitedEmail", "TargetRole")
                        .IsUnique()
                        .HasDatabaseName("UX_company_invitations_open_per_company_email_role")
                        .HasFilter("state::text = 'pending'");

                    b.ToTable("company_invitations", "b2b", t =>
                        {
                            t.HasCheckConstraint("chk_company_invitations_role", "target_role::text IN ('companies.admin','buyer','approver')");

                            t.HasCheckConstraint("chk_company_invitations_state", "state::text IN ('pending','accepted','declined','expired')");
                        });
                });

            modelBuilder.Entity("BackendApi.Modules.B2B.Entities.CompanyMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("citext")
                        .HasColumnName("role");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_company_memberships_user");

                    b.HasIndex("CompanyId", "Role")
                        .HasDatabaseName("IX_company_memberships_company_role");

                    b.HasIndex("CompanyId", "UserId", "Role")
                        .IsUnique()
                        .HasDatabaseName("UX_company_memberships_company_user_role");

                    b.ToTable("company_memberships", "b2b", t =>
                        {
                            t.HasCheckConstraint("chk_company_memberships_role", "role::text IN ('companies.admin','buyer','approver')");
                        });
                });

            modelBuilder.Entity("BackendApi.Modules.B2B.Entities.Quote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApproverRejectionNote")
                        .HasColumnType("text")
                        .HasColumnName("approver_rejection_note");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<Guid?>("CurrentVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_version_id");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("CustomerSuppliedMessageJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("customer_supplied_message");

                    b.Property<DateTimeOffset?>("DecidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decided_at");

                    b.Property<Guid?>("DecidedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("decided_by");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("InternalNote")
                        .HasColumnType("text")
                        .HasColumnName("internal_note");

                    b.Property<bool>("InvoiceBilling")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("invoice_billing");

                    b.Property<string>("MarketCode")
                        .IsRequired()
                        .HasColumnType("citext")
                        .HasColumnName("market_code");

                    b.Property<string>("OriginatingCartSnapshotJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("originating_cart_snapshot");

                    b.Property<Guid?>("OriginatingProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("originating_product_id");

                    b.Property<string>("PoNumber")
                        .HasMaxLength(128)
                        .HasColumnType("text")
                        .HasColumnName("po_number");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at");

                    b.Property<string>("RestrictionPolicySnapshotJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("restriction_policy_snapshot")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("integer")
                        .HasColumnName("schema_version");

                    b.Property<string>("State")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("citext")
                        .HasDefaultValue("requested")
                        .HasColumnName("state");

                    b.Property<DateTimeOffset?>("TerminalAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("terminal_at");

                    b.Property<string>("TerminalReason")
                        .HasColumnType("citext")
                        .HasColumnName("terminal_reason");

                    b.Property<uint>("XminRowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("IX_quotes_expires_at")
                        .HasFilter("state::text IN ('revised','pending-approver')");

                    b.HasIndex("CompanyId", "PoNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_quotes_company_po")
                        .HasFilter("company_id IS NOT NULL AND po_number IS NOT NULL");

                    b.HasIndex("CustomerId", "State")
                        .HasDatabaseName("IX_quotes_customer_state");

                    b.HasIndex("CompanyId", "State", "MarketCode")
                        .HasDatabaseName("IX_quotes_company_state_market")
                        .HasFilter("company_id IS NOT NULL");

                    b.HasIndex("State", "MarketCode", "RequestedAt")
                        .HasDatabaseName("IX_quotes_state_market_requested")
                        .HasFilter("state::text IN ('requested','drafted','revised','pending-approver')");

                    b.ToTable("quotes", "b2b", t =>
                        {
                            t.HasCheckConstraint("chk_quotes_branch_requires_company", "branch_id IS NULL OR company_id IS NOT NULL");

                            t.HasCheckConstraint("chk_quotes_market", "market_code::text IN ('eg','ksa')");

                            t.HasCheckConstraint("chk_quotes_state", "state::text IN ('requested','drafted','revised','pending-approver','accepted','rejected','expired','withdrawn')");
                        });
                });

            modelBuilder.Entity("BackendApi.Modules.B2B.Entities.QuoteMarketSchema", b =>
                {
                    b.Property<string>("MarketCode")
                        .HasColumnType("citext")
                        .HasColumnName("market_code");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<bool>("CompanyVerificationRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("company_verification_required");

                    b.Property<DateTimeOffset>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_from");

                    b.Property<DateTimeOffset?>("EffectiveTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_to");

                    b.Property<string>("HolidaysListJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("holidays_list")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<int>("InvitationTtlDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(14)
                        .HasColumnName("invitation_ttl_days");

                    b.Property<int>("RateLimitPerCompanyPerHour")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(50)
                        .HasColumnName("rate_limit_per_company_per_hour");

                    b.Property<int>("RateLimitPerCustomerPerHour")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(10)
                        .HasColumnName("rate_limit_per_customer_per_hour");

                    b.Property<int>("SlaDecisionBusinessDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(2)
                        .HasColumnName("sla_decision_business_days");

                    b.Property<int>("SlaWarningBusinessDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("sla_warning_business_days");

                    b.Property<decimal>("TaxPreviewDriftThresholdPct")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(5,2)")
                        .HasDefaultValue(5.00m)
                        .HasColumnName("tax_preview_drift_threshold_pct");

                    b.Property<int>("ValidityDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(14)
                        .HasColumnName("validity_days");

                    b.HasKey("MarketCode", "Version");

                    b.HasIndex("MarketCode")
                        .IsUnique()
                        .HasDatabaseName("UX_quote_market_schemas_active_per_market")
                        .HasFilter("effective_to IS NULL");

                    b.ToTable("quote_market_schemas", "b2b", t =>
                        {
                            t.HasCheckConstraint("chk_qms_drift_in_range", "tax_preview_drift_threshold_pct >= 0 AND tax_preview_drift_threshold_pct <= 100");

                            t.HasCheckConstraint("chk_qms_invitation_ttl_positive", "invitation_ttl_days > 0");

                            t.HasCheckConstraint("chk_qms_market", "market_code::text IN ('eg','ksa')");

                            t.HasCheckConstraint("chk_qms_rate_limits_positive", "rate_limit_per_customer_per_hour > 0 AND rate_limit_per_company_per_hour > 0");

                            t.HasCheckConstraint("chk_qms_sla_nonneg", "sla_decision_business_days >= 0 AND sla_warning_business_days >= 0");

                            t.HasCheckConstraint("chk_qms_validity_positive", "validity_days > 0");
                        });
                });

            modelBuilder.Entity("BackendApi.Modules.B2B.Entities.QuoteStateTransition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<string>("ActorKind")
                        .IsRequired()
                        .HasColumnType("citext")
                        .HasColumnName("actor_kind");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("NewState")
                        .IsRequired()
                        .HasColumnType("citext")
                        .HasColumnName("new_state");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("PriorState")
                        .IsRequired()
                        .HasColumnType("citext")
                        .HasColumnName("prior_state");

                    b.Property<Guid>("QuoteId")
                        .HasColumnType("uuid")
                        .HasColumnName("quote_id");

                    b.Property<string>("ReasonJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("reason");

                    b.HasKey("Id");

                    b.HasIndex("QuoteId", "OccurredAt")
                        .HasDatabaseName("IX_quote_state_transitions_quote_occurred");

                    b.ToTable("quote_state_transitions", "b2b", t =>
                        {
                            t.HasCheckConstraint("chk_qst_actor_kind", "actor_kind::text IN ('customer','buyer','approver','admin_operator','system')");

                            t.HasCheckConstraint("chk_qst_new_state", "new_state::text IN ('requested','drafted','revised','pending-approver','accepted','rejected','expired','withdrawn')");

                            t.HasCheckConstraint("chk_qst_prior_state", "prior_state::text IN ('__none__','requested','drafted','revised','pending-approver','accepted','rejected','expired','withdrawn')");
                        });
                });

            modelBuilder.Entity("BackendApi.Modules.B2B.Entities.QuoteVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthoredBy")
                        .HasColumnType("uuid")
                        .HasColumnName("authored_by");

                    b.Property<string>("CustomerRevisionCommentJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("customer_revision_comment");

                    b.Property<string>("LineItemsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("line_items");

                    b.Property<DateTimeOffset>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<Guid>("QuoteId")
                        .HasColumnType("uuid")
                        .HasColumnName("quote_id");

                    b.Property<int>("TermsDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("terms_days");

                    b.Property<string>("TermsTextJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("terms_text");

                    b.Property<string>("TotalsSummaryJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("totals_summary");

                    b.Property<bool>("ValidityExtends")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("validity_extends");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("version_number");

                    b.HasKey("Id");

                    b.HasIndex("QuoteId", "VersionNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_quote_versions_quote_version");

                    b.ToTable("quote_versions", "b2b", t =>
                        {
                            t.HasCheckConstraint("chk_quote_versions_terms_days_nonneg", "terms_days >= 0");

                            t.HasCheckConstraint("chk_quote_versions_version_positive", "version_number > 0");
                        });
                });

            modelBuilder.Entity("BackendApi.Modules.B2B.Entities.QuoteVersionDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("application/pdf")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("GeneratedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("generated_at");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasColumnType("citext")
                        .HasColumnName("locale");

                    b.Property<Guid>("QuoteVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("quote_version_id");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("text")
                        .HasColumnName("storage_key");

                    b.HasKey("Id");

                    b.HasIndex("QuoteVersionId", "Locale")
                        .IsUnique()
                        .HasDatabaseName("UX_quote_version_documents_version_locale");

                    b.ToTable("quote_version_documents", "b2b", t =>
                        {
                            t.HasCheckConstraint("chk_qvd_locale", "locale::text IN ('en','ar')");
                        });
                });

            modelBuilder.Entity("BackendApi.Modules.B2B.Entities.RepeatOrderTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("NameJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("name");

                    b.Property<Guid>("SourceQuoteId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_quote_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("SourceQuoteId");

                    b.HasIndex("CompanyId", "NameJson")
                        .IsUnique()
                        .HasDatabaseName("UX_repeat_order_templates_company_name")
                        .HasFilter("company_id IS NOT NULL");

                    b.HasIndex("UserId", "NameJson")
                        .IsUnique()
                        .HasDatabaseName("UX_repeat_order_templates_user_name")
                        .HasFilter("company_id IS NULL");

                    b.ToTable("repeat_order_templates", "b2b");
                });

            modelBuilder.Entity("BackendApi.Modules.B2B.Entities.CompanyBranch", b =>
                {
                    b.HasOne("BackendApi.Modules.B2B.Entities.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BackendApi.Modules.B2B.Entities.CompanyInvitation", b =>
                {
                    b.HasOne("BackendApi.Modules.B2B.Entities.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BackendApi.Modules.B2B.Entities.CompanyMembership", b =>
                {
                    b.HasOne("BackendApi.Modules.B2B.Entities.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BackendApi.Modules.B2B.Entities.QuoteStateTransition", b =>
                {
                    b.HasOne("BackendApi.Modules.B2B.Entities.Quote", null)
                        .WithMany()
                        .HasForeignKey("QuoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BackendApi.Modules.B2B.Entities.QuoteVersion", b =>
                {
                    b.HasOne("BackendApi.Modules.B2B.Entities.Quote", null)
                        .WithMany()
                        .HasForeignKey("QuoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BackendApi.Modules.B2B.Entities.QuoteVersionDocument", b =>
                {
                    b.HasOne("BackendApi.Modules.B2B.Entities.QuoteVersion", null)
                        .WithMany()
                        .HasForeignKey("QuoteVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BackendApi.Modules.B2B.Entities.RepeatOrderTemplate", b =>
                {
                    b.HasOne("BackendApi.Modules.B2B.Entities.Quote", null)
                        .WithMany()
                        .HasForeignKey("SourceQuoteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
