using System.Reflection;
using System.Text.Json;
using QuestPDF.Drawing;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace BackendApi.Modules.Pdf.Templates;

public sealed class TaxInvoiceTemplate(LocaleCode locale, object data) : IDocument
{
    private static bool _fontRegistered;

    public DocumentMetadata GetMetadata() => DocumentMetadata.Default;

    public void Compose(IDocumentContainer container)
    {
        EnsureArabicFontRegistered();

        var title = locale == LocaleCode.AR ? "فاتورة ضريبية" : "Tax Invoice";
        var payload = JsonSerializer.Serialize(data, new JsonSerializerOptions { WriteIndented = true });

        container.Page(page =>
        {
            page.Size(PageSizes.A4);
            page.Margin(30);
            page.DefaultTextStyle(x => x.FontFamily(locale == LocaleCode.AR ? "NotoNaskhArabic" : Fonts.Arial));
            page.Content().Column(column =>
            {
                column.Spacing(12);
                if (locale == LocaleCode.AR)
                {
                    column.Item().AlignRight().Text(title).FontSize(20).SemiBold();
                    column.Item().AlignRight().Text(payload).FontSize(10);
                }
                else
                {
                    column.Item().Text(title).FontSize(20).SemiBold();
                    column.Item().Text(payload).FontSize(10);
                }
            });
            page.Footer().AlignCenter().Text(text =>
            {
                text.Span(locale == LocaleCode.AR ? "تم الإنشاء بواسطة BuidSass" : "Generated by BuidSass");
            });
        });
    }

    private static void EnsureArabicFontRegistered()
    {
        if (_fontRegistered)
        {
            return;
        }

        var assembly = Assembly.GetExecutingAssembly();
        var fontResource = assembly
            .GetManifestResourceNames()
            .FirstOrDefault(x => x.EndsWith("Noto_Naskh_Arabic-Regular.ttf", StringComparison.Ordinal));

        if (fontResource is null)
        {
            _fontRegistered = true;
            return;
        }

        using var stream = assembly.GetManifestResourceStream(fontResource);
        if (stream is not null)
        {
            FontManager.RegisterFontWithCustomName("NotoNaskhArabic", stream);
        }

        _fontRegistered = true;
    }
}
