// <auto-generated />
using System;
using BackendApi.Modules.Cms.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BackendApi.Modules.Cms.Persistence.Migrations
{
    [DbContext(typeof(CmsDbContext))]
    [Migration("20260502053747_AddCmsAssetMarketCode")]
    partial class AddCmsAssetMarketCode
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("cms")
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BackendApi.Modules.Cms.Entities.BannerCampaignBinding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("BannerId")
                        .HasColumnType("uuid");

                    b.Property<string>("BindingStateWire")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("active")
                        .HasColumnName("BindingState");

                    b.Property<DateTimeOffset>("BoundAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ReleaseActorId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReleaseReasonNote")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ReleasedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VersionId")
                        .HasColumnType("uuid");

                    b.Property<uint>("Xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("BannerId", "BindingStateWire")
                        .HasDatabaseName("IX_cms_banner_binding_banner");

                    b.HasIndex("CampaignId", "BindingStateWire")
                        .HasDatabaseName("IX_cms_banner_binding_campaign");

                    b.ToTable("banner_campaign_bindings", "cms", t =>
                        {
                            t.HasCheckConstraint("CK_cms_banner_binding_release_consistency", "(\"BindingState\" = 'active' AND \"ReleasedAtUtc\" IS NULL) OR (\"BindingState\" <> 'active' AND \"ReleasedAtUtc\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_cms_banner_binding_state", "\"BindingState\" IN ('active','released_due_to_campaign_deactivation','released_by_editor')");
                        });
                });

            modelBuilder.Entity("BackendApi.Modules.Cms.Entities.BannerSlot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ArchiveReasonNote")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ArchivedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("AssetIdAr")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssetIdEn")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CtaHealthWire")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("not_applicable")
                        .HasColumnName("CtaHealth");

                    b.Property<string>("CtaKindWire")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("CtaKind");

                    b.Property<string>("CtaTarget")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("EditorSaveAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("HeadlineAr")
                        .HasColumnType("text");

                    b.Property<string>("HeadlineEn")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastStaleAlertAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastStaleAlertDismissedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MarketCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OwnerActorId")
                        .HasColumnType("uuid");

                    b.Property<bool>("OwnershipOrphaned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("PriorityWithinSlot")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(100);

                    b.Property<DateTimeOffset?>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ScheduledEndUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ScheduledStartUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SlotKindWire")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("SlotKind");

                    b.Property<string>("StateWire")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("draft")
                        .HasColumnName("State");

                    b.Property<string>("SubheadAr")
                        .HasColumnType("text");

                    b.Property<string>("SubheadEn")
                        .HasColumnType("text");

                    b.Property<Guid?>("VendorId")
                        .HasColumnType("uuid");

                    b.Property<uint>("Xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("VendorId")
                        .HasDatabaseName("IX_cms_banners_vendor")
                        .HasFilter("\"VendorId\" IS NOT NULL");

                    b.HasIndex("OwnerActorId", "StateWire")
                        .HasDatabaseName("IX_cms_banners_owner_state");

                    b.HasIndex("StateWire", "ScheduledEndUtc")
                        .HasDatabaseName("IX_cms_banners_worker_end_scan");

                    b.HasIndex("StateWire", "ScheduledStartUtc")
                        .HasDatabaseName("IX_cms_banners_worker_start_scan");

                    b.HasIndex("StateWire", "MarketCode", "SlotKindWire", "PriorityWithinSlot", "CreatedAtUtc")
                        .HasDatabaseName("IX_cms_banners_storefront_read");

                    b.ToTable("banner_slots", "cms", t =>
                        {
                            t.HasCheckConstraint("CK_cms_banners_cta_health", "\"CtaHealth\" IN ('verified','broken','transient_unverified','not_applicable')");

                            t.HasCheckConstraint("CK_cms_banners_cta_kind", "\"CtaKind\" IN ('link','category','product','bundle','external_url','none')");

                            t.HasCheckConstraint("CK_cms_banners_headline_ar_len", "\"HeadlineAr\" IS NULL OR char_length(\"HeadlineAr\") <= 120");

                            t.HasCheckConstraint("CK_cms_banners_headline_en_len", "\"HeadlineEn\" IS NULL OR char_length(\"HeadlineEn\") <= 120");

                            t.HasCheckConstraint("CK_cms_banners_market_code", "\"MarketCode\" IN ('EG','KSA','*')");

                            t.HasCheckConstraint("CK_cms_banners_schedule_window", "\"ScheduledStartUtc\" IS NULL OR \"ScheduledEndUtc\" IS NULL OR \"ScheduledEndUtc\" > \"ScheduledStartUtc\"");

                            t.HasCheckConstraint("CK_cms_banners_slot_kind", "\"SlotKind\" IN ('hero_top','category_strip','footer_strip','home_secondary')");

                            t.HasCheckConstraint("CK_cms_banners_state", "\"State\" IN ('draft','scheduled','live','archived')");

                            t.HasCheckConstraint("CK_cms_banners_subhead_ar_len", "\"SubheadAr\" IS NULL OR char_length(\"SubheadAr\") <= 240");

                            t.HasCheckConstraint("CK_cms_banners_subhead_en_len", "\"SubheadEn\" IS NULL OR char_length(\"SubheadEn\") <= 240");
                        });
                });

            modelBuilder.Entity("BackendApi.Modules.Cms.Entities.BlogArticle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ArchiveReasonNote")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ArchivedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AuthoredLocale")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Body")
                        .HasColumnType("text");

                    b.Property<string>("CategoryWire")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Category");

                    b.Property<Guid?>("CoverAssetId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset>("EditorSaveAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("LastStaleAlertAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastStaleAlertDismissedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MarketCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OwnerActorId")
                        .HasColumnType("uuid");

                    b.Property<bool>("OwnershipOrphaned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset?>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ScheduledPublishAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SeoMetaDescription")
                        .HasColumnType("text");

                    b.Property<string>("SeoMetaTitle")
                        .HasColumnType("text");

                    b.Property<Guid?>("SeoOgImageId")
                        .HasColumnType("uuid");

                    b.Property<string>("SeoSchemaOrgKind")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("BlogPosting");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StateWire")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("draft")
                        .HasColumnName("State");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("VendorId")
                        .HasColumnType("uuid");

                    b.Property<uint>("Xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("StateWire", "ScheduledPublishAtUtc")
                        .HasDatabaseName("IX_cms_blog_worker_scan");

                    b.HasIndex("MarketCode", "AuthoredLocale", "Slug")
                        .IsUnique()
                        .HasDatabaseName("UX_cms_blog_slug_market_locale");

                    b.HasIndex("StateWire", "MarketCode", "CategoryWire", "PublishedAtUtc")
                        .HasDatabaseName("IX_cms_blog_storefront_read");

                    b.ToTable("blog_articles", "cms", t =>
                        {
                            t.HasCheckConstraint("CK_cms_blog_authored_locale", "\"AuthoredLocale\" IN ('ar','en')");

                            t.HasCheckConstraint("CK_cms_blog_body_len", "\"Body\" IS NULL OR char_length(\"Body\") <= 60000");

                            t.HasCheckConstraint("CK_cms_blog_category", "\"Category\" IN ('tips','news','guides','case_studies','clinical','other')");

                            t.HasCheckConstraint("CK_cms_blog_market_code", "\"MarketCode\" IN ('EG','KSA','*')");

                            t.HasCheckConstraint("CK_cms_blog_seo_kind", "\"SeoSchemaOrgKind\" IN ('Article','BlogPosting','NewsArticle','FAQPage')");

                            t.HasCheckConstraint("CK_cms_blog_seo_meta_description_len", "\"SeoMetaDescription\" IS NULL OR char_length(\"SeoMetaDescription\") <= 160");

                            t.HasCheckConstraint("CK_cms_blog_seo_meta_title_len", "\"SeoMetaTitle\" IS NULL OR char_length(\"SeoMetaTitle\") <= 70");

                            t.HasCheckConstraint("CK_cms_blog_slug_pattern", "\"Slug\" ~ '^[a-z0-9]+(-[a-z0-9]+)*$'");

                            t.HasCheckConstraint("CK_cms_blog_state", "\"State\" IN ('draft','scheduled','live','archived')");
                        });
                });

            modelBuilder.Entity("BackendApi.Modules.Cms.Entities.CmsAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset?>("DereferencedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IntendedLocale")
                        .HasColumnType("text");

                    b.Property<string>("MarketCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("*");

                    b.Property<string>("Mime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OriginalFilename")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<Guid>("StorageObjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("StorageObjectStateWire")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("active")
                        .HasColumnName("StorageObjectState");

                    b.Property<DateTimeOffset?>("SweptAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("UploadedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UploadedByActorId")
                        .HasColumnType("uuid");

                    b.Property<uint>("Xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("StorageObjectStateWire", "DereferencedAtUtc")
                        .HasDatabaseName("IX_cms_assets_gc_scan");

                    b.ToTable("assets", "cms", t =>
                        {
                            t.HasCheckConstraint("CK_cms_asset_intended_locale", "\"IntendedLocale\" IS NULL OR \"IntendedLocale\" IN ('ar','en','*')");

                            t.HasCheckConstraint("CK_cms_asset_market_code", "\"MarketCode\" IN ('EG','KSA','*')");

                            t.HasCheckConstraint("CK_cms_asset_size_positive", "\"SizeBytes\" >= 0");

                            t.HasCheckConstraint("CK_cms_asset_storage_state", "\"StorageObjectState\" IN ('active','swept')");
                        });
                });

            modelBuilder.Entity("BackendApi.Modules.Cms.Entities.CmsMarketSchema", b =>
                {
                    b.Property<string>("MarketCode")
                        .HasColumnType("text");

                    b.Property<int>("AssetGracePeriodDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(7);

                    b.Property<int>("BannerMaxLivePerSlot")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(5);

                    b.Property<int>("DraftStalenessAlertDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(30);

                    b.Property<int>("FeaturedSectionMaxReferences")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(24);

                    b.Property<DateTimeOffset>("LastEditedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("LastEditedByActorId")
                        .HasColumnType("uuid");

                    b.Property<int>("PreviewTokenDefaultTtlHours")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(24);

                    b.Property<uint>("Xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("MarketCode");

                    b.ToTable("market_schemas", "cms", t =>
                        {
                            t.HasCheckConstraint("CK_cms_asset_grace", "\"AssetGracePeriodDays\" BETWEEN 0 AND 30");

                            t.HasCheckConstraint("CK_cms_banner_max_live", "\"BannerMaxLivePerSlot\" BETWEEN 1 AND 10");

                            t.HasCheckConstraint("CK_cms_featured_max_refs", "\"FeaturedSectionMaxReferences\" BETWEEN 1 AND 100");

                            t.HasCheckConstraint("CK_cms_market_code", "\"MarketCode\" IN ('EG','KSA','*')");

                            t.HasCheckConstraint("CK_cms_preview_ttl", "\"PreviewTokenDefaultTtlHours\" BETWEEN 1 AND 168");

                            t.HasCheckConstraint("CK_cms_stale_alert", "\"DraftStalenessAlertDays\" BETWEEN 7 AND 365");
                        });
                });

            modelBuilder.Entity("BackendApi.Modules.Cms.Entities.CmsPreviewToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ActorRoleAtMint")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityKindWire")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("EntityKind");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("MintedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("MintedByActorId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("RevokedByActorId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<Guid>("VersionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAtUtc")
                        .HasDatabaseName("IX_cms_preview_cleanup_scan");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("UX_cms_preview_token_hash");

                    b.ToTable("preview_tokens", "cms", t =>
                        {
                            t.HasCheckConstraint("CK_cms_preview_entity_kind", "\"EntityKind\" IN ('banner_slot','featured_section','faq_entry','blog_article','legal_page_version')");

                            t.HasCheckConstraint("CK_cms_preview_expires_after_mint", "\"ExpiresAtUtc\" > \"MintedAtUtc\"");
                        });
                });

            modelBuilder.Entity("BackendApi.Modules.Cms.Entities.FaqEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AnswerAr")
                        .HasColumnType("text");

                    b.Property<string>("AnswerEn")
                        .HasColumnType("text");

                    b.Property<string>("ArchiveReasonNote")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ArchivedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CategoryWire")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Category");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(100);

                    b.Property<DateTimeOffset>("EditorSaveAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("LastStaleAlertAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastStaleAlertDismissedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MarketCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OwnerActorId")
                        .HasColumnType("uuid");

                    b.Property<bool>("OwnershipOrphaned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset?>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("QuestionAr")
                        .HasColumnType("text");

                    b.Property<string>("QuestionEn")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ScheduledPublishAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StateWire")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("draft")
                        .HasColumnName("State");

                    b.Property<Guid?>("VendorId")
                        .HasColumnType("uuid");

                    b.Property<uint>("Xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CategoryWire", "MarketCode")
                        .HasDatabaseName("IX_cms_faq_admin_grouping");

                    b.HasIndex("StateWire", "MarketCode", "CategoryWire", "DisplayOrder", "CreatedAtUtc")
                        .HasDatabaseName("IX_cms_faq_storefront_read");

                    b.ToTable("faq_entries", "cms", t =>
                        {
                            t.HasCheckConstraint("CK_cms_faq_answer_ar_len", "\"AnswerAr\" IS NULL OR char_length(\"AnswerAr\") <= 4000");

                            t.HasCheckConstraint("CK_cms_faq_answer_en_len", "\"AnswerEn\" IS NULL OR char_length(\"AnswerEn\") <= 4000");

                            t.HasCheckConstraint("CK_cms_faq_category", "\"Category\" IN ('ordering','payment','shipping','returns','account','verification','b2b','other')");

                            t.HasCheckConstraint("CK_cms_faq_market_code", "\"MarketCode\" IN ('EG','KSA','*')");

                            t.HasCheckConstraint("CK_cms_faq_question_ar_len", "\"QuestionAr\" IS NULL OR char_length(\"QuestionAr\") <= 250");

                            t.HasCheckConstraint("CK_cms_faq_question_en_len", "\"QuestionEn\" IS NULL OR char_length(\"QuestionEn\") <= 250");

                            t.HasCheckConstraint("CK_cms_faq_state", "\"State\" IN ('draft','scheduled','live','archived')");
                        });
                });

            modelBuilder.Entity("BackendApi.Modules.Cms.Entities.FeaturedSection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ArchiveReasonNote")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ArchivedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("DisplayPriority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(100);

                    b.Property<DateTimeOffset>("EditorSaveAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("LastPartialBrokenAlertAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastStaleAlertAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastStaleAlertDismissedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MarketCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OwnerActorId")
                        .HasColumnType("uuid");

                    b.Property<bool>("OwnershipOrphaned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset?>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReferencesJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("References")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<DateTimeOffset?>("ScheduledPublishAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SectionKindWire")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("SectionKind");

                    b.Property<string>("StateWire")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("draft")
                        .HasColumnName("State");

                    b.Property<string>("SubtitleAr")
                        .HasColumnType("text");

                    b.Property<string>("SubtitleEn")
                        .HasColumnType("text");

                    b.Property<string>("TitleAr")
                        .HasColumnType("text");

                    b.Property<string>("TitleEn")
                        .HasColumnType("text");

                    b.Property<Guid?>("VendorId")
                        .HasColumnType("uuid");

                    b.Property<uint>("Xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("StateWire", "ScheduledPublishAtUtc")
                        .HasDatabaseName("IX_cms_featured_worker_scan");

                    b.HasIndex("StateWire", "MarketCode", "SectionKindWire", "DisplayPriority", "CreatedAtUtc")
                        .HasDatabaseName("IX_cms_featured_storefront_read");

                    b.ToTable("featured_sections", "cms", t =>
                        {
                            t.HasCheckConstraint("CK_cms_featured_market_code", "\"MarketCode\" IN ('EG','KSA','*')");

                            t.HasCheckConstraint("CK_cms_featured_refs_size", "jsonb_array_length(\"References\") BETWEEN 0 AND 100");

                            t.HasCheckConstraint("CK_cms_featured_section_kind", "\"SectionKind\" IN ('home_top','home_mid','category_landing','b2b_landing')");

                            t.HasCheckConstraint("CK_cms_featured_state", "\"State\" IN ('draft','scheduled','live','archived')");
                        });
                });

            modelBuilder.Entity("BackendApi.Modules.Cms.Entities.LegalPageVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("BodyAr")
                        .HasColumnType("text");

                    b.Property<string>("BodyEn")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset>("EditorSaveAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("EffectiveAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastStaleAlertAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastStaleAlertDismissedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LegalPageKindWire")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("LegalPageKind");

                    b.Property<string>("MarketCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OwnerActorId")
                        .HasColumnType("uuid");

                    b.Property<bool>("OwnershipOrphaned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset?>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StateWire")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("draft")
                        .HasColumnName("State");

                    b.Property<DateTimeOffset?>("SupersededAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("SupersededByVersionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("VendorId")
                        .HasColumnType("uuid");

                    b.Property<string>("VersionLabel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<uint>("Xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("StateWire", "EffectiveAtUtc")
                        .HasDatabaseName("IX_cms_legal_worker_scan");

                    b.HasIndex("LegalPageKindWire", "MarketCode", "StateWire", "EffectiveAtUtc")
                        .HasDatabaseName("IX_cms_legal_history");

                    b.ToTable("legal_page_versions", "cms", t =>
                        {
                            t.HasCheckConstraint("CK_cms_legal_kind", "\"LegalPageKind\" IN ('terms','privacy','returns','cookies')");

                            t.HasCheckConstraint("CK_cms_legal_market_code", "\"MarketCode\" IN ('EG','KSA','*')");

                            t.HasCheckConstraint("CK_cms_legal_state", "\"State\" IN ('draft','scheduled','live','superseded')");

                            t.HasCheckConstraint("CK_cms_legal_supersede_consistency", "(\"State\" = 'superseded' AND \"SupersededAtUtc\" IS NOT NULL AND \"SupersededByVersionId\" IS NOT NULL) OR (\"State\" <> 'superseded' AND \"SupersededAtUtc\" IS NULL AND \"SupersededByVersionId\" IS NULL)");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
