// <auto-generated />
using System;
using BackendApi.Modules.TaxInvoices.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BackendApi.Modules.TaxInvoices.Persistence.Migrations
{
    [DbContext(typeof(InvoicesDbContext))]
    [Migration("20260425231641_TaxInvoices_DeepReviewFixes")]
    partial class TaxInvoices_DeepReviewFixes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("invoices")
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BackendApi.Modules.TaxInvoices.Entities.CreditNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreditNoteNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("DiscountMinor")
                        .HasColumnType("bigint");

                    b.Property<long>("GrandTotalMinor")
                        .HasColumnType("bigint");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<string>("MarketCode")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<string>("PdfBlobKey")
                        .HasColumnType("text");

                    b.Property<string>("PdfSha256")
                        .HasColumnType("text");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<Guid?>("RefundId")
                        .HasColumnType("uuid");

                    b.Property<int>("RenderAttempts")
                        .HasColumnType("integer");

                    b.Property<long>("ShippingMinor")
                        .HasColumnType("bigint");

                    b.Property<string>("State")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("citext")
                        .HasDefaultValue("pending");

                    b.Property<long>("SubtotalMinor")
                        .HasColumnType("bigint");

                    b.Property<long>("TaxMinor")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ZatcaQrB64")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreditNoteNumber")
                        .IsUnique();

                    b.HasIndex("InvoiceId");

                    b.HasIndex("RefundId")
                        .IsUnique()
                        .HasDatabaseName("IX_invoices_credit_notes_refund_unique")
                        .HasFilter("\"RefundId\" IS NOT NULL");

                    b.HasIndex("MarketCode", "IssuedAt")
                        .HasDatabaseName("IX_invoices_credit_notes_market_issued");

                    b.ToTable("credit_notes", "invoices", t =>
                        {
                            t.HasCheckConstraint("CK_invoices_credit_notes_state_enum", "\"State\" IN ('pending','rendered','delivered','failed')");
                        });
                });

            modelBuilder.Entity("BackendApi.Modules.TaxInvoices.Entities.CreditNoteLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreditNoteId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("InvoiceLineId")
                        .HasColumnType("uuid");

                    b.Property<long>("LineDiscountMinor")
                        .HasColumnType("bigint");

                    b.Property<long>("LineTaxMinor")
                        .HasColumnType("bigint");

                    b.Property<long>("LineTotalMinor")
                        .HasColumnType("bigint");

                    b.Property<string>("MarketCode")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Qty")
                        .HasColumnType("integer");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<int>("TaxRateBp")
                        .HasColumnType("integer");

                    b.Property<long>("UnitPriceMinor")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CreditNoteId");

                    b.HasIndex("InvoiceLineId");

                    b.HasIndex("MarketCode", "CreditNoteId")
                        .HasDatabaseName("IX_invoices_credit_note_lines_market_cn");

                    b.ToTable("credit_note_lines", "invoices", t =>
                        {
                            t.HasCheckConstraint("CK_invoices_credit_note_lines_qty_positive", "\"Qty\" > 0");
                        });
                });

            modelBuilder.Entity("BackendApi.Modules.TaxInvoices.Entities.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("B2bPoNumber")
                        .HasColumnType("text");

                    b.Property<string>("BillToJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<long>("DiscountMinor")
                        .HasColumnType("bigint");

                    b.Property<long>("GrandTotalMinor")
                        .HasColumnType("bigint");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<string>("MarketCode")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("PdfBlobKey")
                        .HasColumnType("text");

                    b.Property<string>("PdfSha256")
                        .HasColumnType("text");

                    b.Property<Guid>("PriceExplanationId")
                        .HasColumnType("uuid");

                    b.Property<int>("RenderAttempts")
                        .HasColumnType("integer");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("SellerJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<long>("ShippingMinor")
                        .HasColumnType("bigint");

                    b.Property<string>("State")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("citext")
                        .HasDefaultValue("pending");

                    b.Property<long>("SubtotalMinor")
                        .HasColumnType("bigint");

                    b.Property<long>("TaxMinor")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("XmlBlobKey")
                        .HasColumnType("text");

                    b.Property<string>("ZatcaQrB64")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceNumber")
                        .IsUnique();

                    b.HasIndex("OrderId")
                        .IsUnique()
                        .HasDatabaseName("IX_invoices_invoices_order");

                    b.HasIndex("State")
                        .HasDatabaseName("IX_invoices_invoices_state");

                    b.HasIndex("AccountId", "IssuedAt")
                        .HasDatabaseName("IX_invoices_invoices_account_issued");

                    b.HasIndex("MarketCode", "IssuedAt")
                        .HasDatabaseName("IX_invoices_invoices_market_issued");

                    b.ToTable("invoices", "invoices", t =>
                        {
                            t.HasCheckConstraint("CK_invoices_invoices_grand_total_non_negative", "\"GrandTotalMinor\" >= 0");

                            t.HasCheckConstraint("CK_invoices_invoices_state_enum", "\"State\" IN ('pending','rendered','delivered','failed')");
                        });
                });

            modelBuilder.Entity("BackendApi.Modules.TaxInvoices.Entities.InvoiceLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid");

                    b.Property<long>("LineDiscountMinor")
                        .HasColumnType("bigint");

                    b.Property<long>("LineTaxMinor")
                        .HasColumnType("bigint");

                    b.Property<long>("LineTotalMinor")
                        .HasColumnType("bigint");

                    b.Property<string>("MarketCode")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OrderLineId")
                        .HasColumnType("uuid");

                    b.Property<int>("Qty")
                        .HasColumnType("integer");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<int>("TaxRateBp")
                        .HasColumnType("integer");

                    b.Property<long>("UnitPriceMinor")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("MarketCode", "InvoiceId")
                        .HasDatabaseName("IX_invoices_invoice_lines_market_invoice");

                    b.ToTable("invoice_lines", "invoices", t =>
                        {
                            t.HasCheckConstraint("CK_invoices_invoice_lines_qty_positive", "\"Qty\" > 0");

                            t.HasCheckConstraint("CK_invoices_invoice_lines_tax_rate_bp_bounds", "\"TaxRateBp\" >= 0 AND \"TaxRateBp\" <= 10000");
                        });
                });

            modelBuilder.Entity("BackendApi.Modules.TaxInvoices.Entities.InvoiceRenderJob", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreditNoteId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("InvoiceId")
                        .HasColumnType("uuid");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<string>("MarketCode")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<DateTimeOffset>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("State")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("citext")
                        .HasDefaultValue("queued");

                    b.HasKey("Id");

                    b.HasIndex("MarketCode", "NextAttemptAt")
                        .HasDatabaseName("IX_invoices_render_jobs_market_attempt");

                    b.HasIndex("State", "NextAttemptAt")
                        .HasDatabaseName("IX_invoices_render_jobs_pending")
                        .HasFilter("\"State\" IN ('queued','failed','rendering')");

                    b.ToTable("invoice_render_jobs", "invoices", t =>
                        {
                            t.HasCheckConstraint("CK_invoices_render_jobs_state_enum", "\"State\" IN ('queued','rendering','done','failed')");

                            t.HasCheckConstraint("CK_invoices_render_jobs_target_xor", "(\"InvoiceId\" IS NOT NULL)::int + (\"CreditNoteId\" IS NOT NULL)::int = 1");
                        });
                });

            modelBuilder.Entity("BackendApi.Modules.TaxInvoices.Entities.InvoiceTemplate", b =>
                {
                    b.Property<string>("MarketCode")
                        .HasColumnType("citext");

                    b.Property<string>("BankDetailsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("FooterHtmlAr")
                        .HasColumnType("text");

                    b.Property<string>("FooterHtmlEn")
                        .HasColumnType("text");

                    b.Property<string>("SellerAddressAr")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SellerAddressEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SellerLegalNameAr")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SellerLegalNameEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SellerVatNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByAccountId")
                        .HasColumnType("uuid");

                    b.HasKey("MarketCode");

                    b.ToTable("invoice_templates", "invoices");
                });

            modelBuilder.Entity("BackendApi.Modules.TaxInvoices.Entities.InvoicesOutboxEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CommittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DispatchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<string>("MarketCode")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.HasKey("Id");

                    b.HasIndex("AggregateId");

                    b.HasIndex("CommittedAt")
                        .HasDatabaseName("IX_invoices_outbox_pending")
                        .HasFilter("\"DispatchedAt\" IS NULL");

                    b.HasIndex("MarketCode", "CommittedAt")
                        .HasDatabaseName("IX_invoices_outbox_market_committed");

                    b.ToTable("invoices_outbox", "invoices");
                });

            modelBuilder.Entity("BackendApi.Modules.TaxInvoices.Entities.SubscriptionCheckpoint", b =>
                {
                    b.Property<string>("SourceModule")
                        .HasColumnType("citext");

                    b.Property<string>("EventType")
                        .HasColumnType("citext");

                    b.Property<long>("LastObservedOutboxId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("SourceModule", "EventType");

                    b.ToTable("subscription_checkpoints", "invoices");
                });

            modelBuilder.Entity("BackendApi.Modules.TaxInvoices.Entities.CreditNote", b =>
                {
                    b.HasOne("BackendApi.Modules.TaxInvoices.Entities.Invoice", "Invoice")
                        .WithMany("CreditNotes")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("BackendApi.Modules.TaxInvoices.Entities.CreditNoteLine", b =>
                {
                    b.HasOne("BackendApi.Modules.TaxInvoices.Entities.CreditNote", "CreditNote")
                        .WithMany("Lines")
                        .HasForeignKey("CreditNoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreditNote");
                });

            modelBuilder.Entity("BackendApi.Modules.TaxInvoices.Entities.InvoiceLine", b =>
                {
                    b.HasOne("BackendApi.Modules.TaxInvoices.Entities.Invoice", "Invoice")
                        .WithMany("Lines")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("BackendApi.Modules.TaxInvoices.Entities.CreditNote", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("BackendApi.Modules.TaxInvoices.Entities.Invoice", b =>
                {
                    b.Navigation("CreditNotes");

                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
