// <auto-generated />
using System;
using BackendApi.Modules.Reviews.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BackendApi.Modules.Reviews.Persistence.Migrations
{
    [DbContext(typeof(ReviewsDbContext))]
    [Migration("20260507080502_MakeModerationDecisionFromStateNullable")]
    partial class MakeModerationDecisionFromStateNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("reviews")
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BackendApi.Modules.Reviews.Entities.ProductRatingAggregate", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("MarketCode")
                        .HasColumnType("text");

                    b.Property<decimal?>("AvgRating")
                        .HasColumnType("numeric(3,2)");

                    b.Property<int>("Distribution1")
                        .HasColumnType("integer");

                    b.Property<int>("Distribution2")
                        .HasColumnType("integer");

                    b.Property<int>("Distribution3")
                        .HasColumnType("integer");

                    b.Property<int>("Distribution4")
                        .HasColumnType("integer");

                    b.Property<int>("Distribution5")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("LastUpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("integer");

                    b.Property<Guid?>("VendorId")
                        .HasColumnType("uuid");

                    b.HasKey("ProductId", "MarketCode");

                    b.HasIndex("LastUpdatedUtc")
                        .HasDatabaseName("IX_pra_last_updated");

                    b.HasIndex("VendorId")
                        .HasDatabaseName("IX_pra_vendor")
                        .HasFilter("\"VendorId\" IS NOT NULL");

                    b.ToTable("product_rating_aggregates", "reviews", t =>
                        {
                            t.HasCheckConstraint("CK_pra_avg_null_iff_count_zero", "(\"ReviewCount\" = 0 AND \"AvgRating\" IS NULL) OR (\"ReviewCount\" > 0 AND \"AvgRating\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_pra_avg_rating_range", "\"AvgRating\" IS NULL OR (\"AvgRating\" >= 1.00 AND \"AvgRating\" <= 5.00)");

                            t.HasCheckConstraint("CK_pra_count_equals_buckets_sum", "\"ReviewCount\" = \"Distribution1\" + \"Distribution2\" + \"Distribution3\" + \"Distribution4\" + \"Distribution5\"");

                            t.HasCheckConstraint("CK_pra_dist_buckets_nonneg", "\"Distribution1\" >= 0 AND \"Distribution2\" >= 0 AND \"Distribution3\" >= 0 AND \"Distribution4\" >= 0 AND \"Distribution5\" >= 0");

                            t.HasCheckConstraint("CK_pra_market_code", "\"MarketCode\" IN ('SA','EG')");

                            t.HasCheckConstraint("CK_pra_review_count_nonneg", "\"ReviewCount\" >= 0");
                        });
                });

            modelBuilder.Entity("BackendApi.Modules.Reviews.Entities.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DeliveredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EditCount")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<string[]>("FilterTripTerms")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasDefaultValueSql("'{}'::text[]");

                    b.Property<string>("Headline")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MarketCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("MediaAttachmentReviewRequired")
                        .HasColumnType("boolean");

                    b.Property<string>("MediaUrlsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("MediaUrls")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<Guid>("OrderLineId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("PendingModerationStartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StateChangedAdminNote")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("StateChangedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("StateChangedByActorId")
                        .HasColumnType("uuid");

                    b.Property<string>("StateChangedReasonNote")
                        .HasColumnType("text");

                    b.Property<string>("TriggeredBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("VendorId")
                        .HasColumnType("uuid");

                    b.Property<uint>("Xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("State")
                        .HasDatabaseName("IX_reviews_state")
                        .HasFilter("\"State\" IN ('pending_moderation','flagged')");

                    b.HasIndex("VendorId")
                        .HasDatabaseName("IX_reviews_vendor")
                        .HasFilter("\"VendorId\" IS NOT NULL");

                    b.HasIndex("CustomerId", "State")
                        .HasDatabaseName("IX_reviews_customer_state");

                    b.HasIndex("MarketCode", "PendingModerationStartedAt")
                        .HasDatabaseName("IX_reviews_market_pending_age")
                        .HasFilter("\"State\" = 'pending_moderation'");

                    b.HasIndex("ProductId", "MarketCode", "State")
                        .HasDatabaseName("IX_reviews_product_market_state");

                    b.ToTable("reviews", "reviews", t =>
                        {
                            t.HasCheckConstraint("CK_reviews_body_len", "char_length(\"Body\") BETWEEN 1 AND 4000");

                            t.HasCheckConstraint("CK_reviews_headline_len", "char_length(\"Headline\") BETWEEN 1 AND 100");

                            t.HasCheckConstraint("CK_reviews_locale", "\"Locale\" IN ('ar','en')");

                            t.HasCheckConstraint("CK_reviews_market_code", "\"MarketCode\" IN ('SA','EG')");

                            t.HasCheckConstraint("CK_reviews_media_max", "jsonb_array_length(\"MediaUrls\") <= 4");

                            t.HasCheckConstraint("CK_reviews_rating_range", "\"Rating\" BETWEEN 1 AND 5");

                            t.HasCheckConstraint("CK_reviews_state", "\"State\" IN ('pending_moderation','visible','flagged','hidden','deleted')");

                            t.HasCheckConstraint("CK_reviews_triggered_by", "\"TriggeredBy\" IN ('customer_submission','customer_edit','community_report_threshold','refund_event','account_locked','account_deleted','moderator_action','manual_super_admin')");
                        });
                });

            modelBuilder.Entity("BackendApi.Modules.Reviews.Entities.ReviewAdminNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ReviewId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ReviewId", "CreatedAtUtc")
                        .HasDatabaseName("IX_review_admin_notes_review_created");

                    b.ToTable("review_admin_notes", "reviews", t =>
                        {
                            t.HasCheckConstraint("CK_review_admin_notes_len", "char_length(\"Note\") BETWEEN 1 AND 4000");
                        });
                });

            modelBuilder.Entity("BackendApi.Modules.Reviews.Entities.ReviewFlag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsQualified")
                        .HasColumnType("boolean");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<string>("QualifyingEvaluationJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("QualifyingEvaluation");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ReporterActorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ReviewId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ReporterActorId", "CreatedAtUtc")
                        .HasDatabaseName("IX_review_flags_reporter_created");

                    b.HasIndex("ReviewId", "ReporterActorId")
                        .IsUnique()
                        .HasDatabaseName("UX_review_flags_review_reporter");

                    b.HasIndex("ReviewId", "IsQualified", "CreatedAtUtc")
                        .HasDatabaseName("IX_review_flags_review_qualified_recent");

                    b.ToTable("review_flags", "reviews", t =>
                        {
                            t.HasCheckConstraint("CK_review_flags_other_note_required", "\"Reason\" <> 'other_with_required_note' OR (\"Note\" IS NOT NULL AND char_length(\"Note\") >= 10)");

                            t.HasCheckConstraint("CK_review_flags_reason", "\"Reason\" IN ('inappropriate_language','spam_or_irrelevant','personal_attack','false_or_misleading','other_with_required_note')");
                        });
                });

            modelBuilder.Entity("BackendApi.Modules.Reviews.Entities.ReviewModerationDecision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid");

                    b.Property<string>("ActorRole")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AdminNote")
                        .HasColumnType("text");

                    b.Property<string>("AfterJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("AfterJsonb");

                    b.Property<string>("BeforeJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("BeforeJsonb");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FromState")
                        .HasColumnType("text");

                    b.Property<string>("ReasonNote")
                        .HasColumnType("text");

                    b.Property<Guid>("ReviewId")
                        .HasColumnType("uuid");

                    b.Property<string>("ToState")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TriggeredBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ActorId", "CreatedAtUtc")
                        .HasDatabaseName("IX_rmd_actor_created");

                    b.HasIndex("ReviewId", "CreatedAtUtc")
                        .HasDatabaseName("IX_rmd_review_created");

                    b.ToTable("review_moderation_decisions", "reviews");
                });

            modelBuilder.Entity("BackendApi.Modules.Reviews.Entities.ReviewsFilterWordlist", b =>
                {
                    b.Property<string>("MarketCode")
                        .HasColumnType("text");

                    b.Property<string>("Term")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByActorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Severity")
                        .HasColumnType("text");

                    b.HasKey("MarketCode", "Term");

                    b.HasIndex("MarketCode")
                        .HasDatabaseName("IX_rfw_market");

                    b.ToTable("reviews_filter_wordlists", "reviews", t =>
                        {
                            t.HasCheckConstraint("CK_rfw_market_code", "\"MarketCode\" IN ('SA','EG')");

                            t.HasCheckConstraint("CK_rfw_severity", "\"Severity\" IS NULL OR \"Severity\" IN ('block','warn')");

                            t.HasCheckConstraint("CK_rfw_term_len", "char_length(\"Term\") BETWEEN 1 AND 200");
                        });
                });

            modelBuilder.Entity("BackendApi.Modules.Reviews.Entities.ReviewsMarketSchema", b =>
                {
                    b.Property<string>("MarketCode")
                        .HasColumnType("text");

                    b.Property<int>("CommunityReportThreshold")
                        .HasColumnType("integer");

                    b.Property<int>("CommunityReportWindowDays")
                        .HasColumnType("integer");

                    b.Property<int>("EditWindowDays")
                        .HasColumnType("integer");

                    b.Property<int>("EligibilityWindowDays")
                        .HasColumnType("integer");

                    b.Property<int>("PendingModerationSlaHours")
                        .HasColumnType("integer");

                    b.Property<int>("ReportQualifyingAccountAgeDays")
                        .HasColumnType("integer");

                    b.Property<bool>("ReportQualifyingRequiresVerifiedBuyer")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UpdatedByActorId")
                        .HasColumnType("uuid");

                    b.Property<uint>("Xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("MarketCode");

                    b.ToTable("reviews_market_schemas", "reviews", t =>
                        {
                            t.HasCheckConstraint("CK_rms_community_report_window", "\"CommunityReportWindowDays\" > 0");

                            t.HasCheckConstraint("CK_rms_community_threshold", "\"CommunityReportThreshold\" BETWEEN 1 AND 10");

                            t.HasCheckConstraint("CK_rms_edit_window", "\"EditWindowDays\" BETWEEN 7 AND 90");

                            t.HasCheckConstraint("CK_rms_eligibility_window", "\"EligibilityWindowDays\" BETWEEN 30 AND 730");

                            t.HasCheckConstraint("CK_rms_market_code", "\"MarketCode\" IN ('SA','EG')");

                            t.HasCheckConstraint("CK_rms_pending_moderation_sla", "\"PendingModerationSlaHours\" > 0");

                            t.HasCheckConstraint("CK_rms_qualifying_age", "\"ReportQualifyingAccountAgeDays\" BETWEEN 0 AND 90");
                        });
                });

            modelBuilder.Entity("BackendApi.Modules.Reviews.Entities.ReviewAdminNote", b =>
                {
                    b.HasOne("BackendApi.Modules.Reviews.Entities.Review", null)
                        .WithMany()
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BackendApi.Modules.Reviews.Entities.ReviewFlag", b =>
                {
                    b.HasOne("BackendApi.Modules.Reviews.Entities.Review", null)
                        .WithMany()
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BackendApi.Modules.Reviews.Entities.ReviewModerationDecision", b =>
                {
                    b.HasOne("BackendApi.Modules.Reviews.Entities.Review", null)
                        .WithMany()
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
