#!/usr/bin/env bash
# Spec 007-b T005 / research §R18 — generate openapi.pricing.commercial.json
# from a running app.
#
# The project uses Microsoft.AspNetCore.OpenApi (registered in Program.cs as
# `app.MapOpenApi()`) which exposes /openapi/v1.json on the dev host. This
# script boots the app on a free port, curls the OpenAPI document, filters
# down to the Pricing commercial-authoring admin paths, and writes the
# resulting per-module document to
# services/backend_api/openapi.pricing.commercial.json.
#
# Spec 007-b owns these admin path prefixes (per contract §1):
#   /v1/admin/commercial/coupons
#   /v1/admin/commercial/promotions
#   /v1/admin/commercial/business-pricing
#   /v1/admin/commercial/campaigns
#   /v1/admin/commercial/preview-profiles
#   /v1/admin/commercial/preview
#   /v1/admin/commercial/approvals
#   /v1/admin/commercial/thresholds
#   /v1/admin/commercial/lookups
#
# The 007-a `pricing.*` paths remain in the existing
# services/backend_api/openapi.pricing.json — those are NOT regenerated by this
# script (engine immutability, plan §Constraints).
#
# Usage:
#   DEFAULT_DB_CONNECTION=<conn> ./scripts/generate-openapi-pricing-commercial.sh
#
# A non-functional database connection is acceptable for OpenAPI export — the
# document is generated from endpoint metadata at startup, not from DB queries.
# The migration step is short-circuited by setting Seeding:Enabled=false in
# the inline config.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PROJ="${REPO_ROOT}/services/backend_api/backend_api.csproj"
OUTPUT="${REPO_ROOT}/services/backend_api/openapi.pricing.commercial.json"
PORT="${PORT:-5102}"

if [[ -z "${DEFAULT_DB_CONNECTION:-}" ]]; then
  echo "ERROR: DEFAULT_DB_CONNECTION must be set (any reachable Postgres URI works for OpenAPI export)."
  exit 2
fi

echo "Starting backend_api on port ${PORT}..."
ASPNETCORE_URLS="http://localhost:${PORT}" \
  ASPNETCORE_ENVIRONMENT=Development \
  Seeding__Enabled=false \
  dotnet run --project "$PROJ" --no-build --launch-profile "" &
SERVER_PID=$!
trap "kill $SERVER_PID 2>/dev/null || true" EXIT

# Wait for /openapi/v1.json to respond.
for i in {1..30}; do
  if curl -sSf "http://localhost:${PORT}/openapi/v1.json" >/dev/null 2>&1; then
    break
  fi
  sleep 1
done

echo "Fetching OpenAPI document..."
curl -sS "http://localhost:${PORT}/openapi/v1.json" \
  | jq '. as $doc
        | .paths
        | with_entries(select(.key
            | test("^/v1/admin/commercial/")))
        as $commercialPaths
        | $doc | .paths = $commercialPaths' \
  > "$OUTPUT"

echo "Wrote $OUTPUT"
echo "Path count: $(jq '.paths | length' "$OUTPUT")"
