// <auto-generated />
using System;
using BackendApi.Modules.Shipping.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BackendApi.Modules.Shipping.Persistence.Migrations
{
    [DbContext(typeof(ShippingDbContext))]
    partial class ShippingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("shipping")
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BackendApi.Modules.Shipping.Domain.DeadLetterLabel", b =>
                {
                    b.Property<Guid>("ShipmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("EnteredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastErrorCode")
                        .HasColumnType("text");

                    b.Property<string>("LastErrorMessageRedacted")
                        .HasColumnType("text");

                    b.Property<string>("Resolution")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ResolvedBy")
                        .HasColumnType("uuid");

                    b.HasKey("ShipmentId");

                    b.ToTable("dead_letter_labels", "shipping", t =>
                        {
                            t.HasCheckConstraint("CK_dead_letter_resolution", "\"Resolution\" IS NULL OR \"Resolution\" IN ('retry','discard','manual_label')");

                            t.HasCheckConstraint("CK_dead_letter_resolved_consistency", "(\"ResolvedAt\" IS NULL AND \"Resolution\" IS NULL) OR (\"ResolvedAt\" IS NOT NULL AND \"Resolution\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("BackendApi.Modules.Shipping.Domain.FeeTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("EffectiveAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("FeeAmount")
                        .HasColumnType("numeric(10,2)");

                    b.Property<Guid>("MethodVersionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("WeightMaxKg")
                        .HasColumnType("numeric(6,2)");

                    b.Property<decimal>("WeightMinKg")
                        .HasColumnType("numeric(6,2)");

                    b.Property<Guid>("ZoneId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MethodVersionId", "ZoneId")
                        .HasDatabaseName("IX_fee_tables_lookup");

                    b.ToTable("fee_tables", "shipping", t =>
                        {
                            t.HasCheckConstraint("CK_fee_tables_currency", "\"Currency\" IN ('SAR','EGP')");

                            t.HasCheckConstraint("CK_fee_tables_fee_amount_nonneg", "\"FeeAmount\" >= 0");

                            t.HasCheckConstraint("CK_fee_tables_weight_range", "\"WeightMinKg\" >= 0 AND \"WeightMaxKg\" > \"WeightMinKg\"");
                        });
                });

            modelBuilder.Entity("BackendApi.Modules.Shipping.Domain.ProviderRouting", b =>
                {
                    b.Property<string>("MarketCode")
                        .HasColumnType("text");

                    b.Property<Guid>("MethodId")
                        .HasColumnType("uuid");

                    b.Property<bool>("AutoFailoverEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("BackupProviderId")
                        .HasColumnType("text");

                    b.Property<int>("FailoverThresholdPct")
                        .HasColumnType("integer");

                    b.Property<int>("FailoverWindowMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("PrimaryProviderId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("MarketCode", "MethodId");

                    b.ToTable("provider_routing", "shipping", t =>
                        {
                            t.HasCheckConstraint("CK_provider_routing_market", "\"MarketCode\" IN ('SA','EG')");

                            t.HasCheckConstraint("CK_provider_routing_primary_neq_backup", "\"BackupProviderId\" IS NULL OR \"BackupProviderId\" <> \"PrimaryProviderId\"");

                            t.HasCheckConstraint("CK_provider_routing_threshold_pct", "\"FailoverThresholdPct\" BETWEEN 10 AND 90");

                            t.HasCheckConstraint("CK_provider_routing_window_minutes", "\"FailoverWindowMinutes\" BETWEEN 1 AND 60");
                        });
                });

            modelBuilder.Entity("BackendApi.Modules.Shipping.Domain.Shipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("EtaMax")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("EtaMin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FailedReason")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("HandedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("InTransitAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LabelPdfBlobUrl")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LabelPurchasedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MarketCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("MethodVersionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ParentShipmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProviderTrackingId")
                        .HasColumnType("text");

                    b.Property<string>("ShipToAddressRedactedJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("Xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique()
                        .HasDatabaseName("UX_shipments_order_id_active")
                        .HasFilter("\"DeletedAt\" IS NULL");

                    b.HasIndex("ParentShipmentId")
                        .HasDatabaseName("IX_shipments_parent");

                    b.HasIndex("ProviderId", "ProviderTrackingId")
                        .HasDatabaseName("IX_shipments_provider_tracking");

                    b.HasIndex("State", "MarketCode")
                        .HasDatabaseName("IX_shipments_active_state")
                        .HasFilter("\"State\" IN ('pending','label_purchased','handed_to_carrier','in_transit','out_for_delivery','delivery_attempted','re_delivered_pending','pending_label_provider_failure')");

                    b.ToTable("shipments", "shipping", t =>
                        {
                            t.HasCheckConstraint("CK_shipments_attempts_nonneg", "\"Attempts\" >= 0");

                            t.HasCheckConstraint("CK_shipments_market_code", "\"MarketCode\" IN ('SA','EG')");

                            t.HasCheckConstraint("CK_shipments_state", "\"State\" IN ('pending','label_purchased','handed_to_carrier','in_transit','out_for_delivery','delivered','delivery_attempted','return_to_sender_initiated','returned_to_sender','delivery_disputed','re_delivered_pending','closed_with_refund','failed_to_create_label','pending_label_provider_failure','dead_letter_label','label_voided')");
                        });
                });

            modelBuilder.Entity("BackendApi.Modules.Shipping.Domain.ShipmentDispute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("ReportedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReportedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResolutionNotes")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ResolvedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ShipmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ShipmentId", "Status")
                        .HasDatabaseName("IX_shipment_disputes_shipment_status");

                    b.ToTable("shipment_disputes", "shipping", t =>
                        {
                            t.HasCheckConstraint("CK_shipment_disputes_reported_by", "\"ReportedBy\" IN ('customer','support_agent')");

                            t.HasCheckConstraint("CK_shipment_disputes_status", "\"Status\" IN ('open','re_delivered','closed_with_refund','closed_no_action')");
                        });
                });

            modelBuilder.Entity("BackendApi.Modules.Shipping.Domain.ShipmentEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InternalStateAtEvent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProviderEventKind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RawPayloadRedactedJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ShipmentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ShipmentId", "OccurredAt")
                        .HasDatabaseName("IX_shipment_events_shipment_occurred");

                    b.ToTable("shipment_events", "shipping");
                });

            modelBuilder.Entity("BackendApi.Modules.Shipping.Domain.ShippingMarketSchema", b =>
                {
                    b.Property<string>("MarketCode")
                        .HasColumnType("text");

                    b.Property<string>("DefaultCurrency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DefaultEtaDaysMax")
                        .HasColumnType("integer");

                    b.Property<int>("DefaultEtaDaysMin")
                        .HasColumnType("integer");

                    b.Property<string>("PostalCodeRegex")
                        .HasColumnType("text");

                    b.Property<int>("SlaBreachThresholdHours")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("MarketCode");

                    b.ToTable("market_schemas", "shipping", t =>
                        {
                            t.HasCheckConstraint("CK_market_schemas_currency", "\"DefaultCurrency\" IN ('SAR','EGP')");

                            t.HasCheckConstraint("CK_market_schemas_eta_days", "\"DefaultEtaDaysMin\" > 0 AND \"DefaultEtaDaysMax\" >= \"DefaultEtaDaysMin\"");

                            t.HasCheckConstraint("CK_market_schemas_market", "\"MarketCode\" IN ('SA','EG')");

                            t.HasCheckConstraint("CK_market_schemas_sla_hours", "\"SlaBreachThresholdHours\" > 0");
                        });
                });

            modelBuilder.Entity("BackendApi.Modules.Shipping.Domain.ShippingMethod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CurrentVersionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DescriptionAr")
                        .HasColumnType("text");

                    b.Property<string>("DescriptionEn")
                        .HasColumnType("text");

                    b.Property<string>("MarketCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MarketCode", "DeletedAt")
                        .HasDatabaseName("IX_shipping_methods_market");

                    b.ToTable("shipping_methods", "shipping", t =>
                        {
                            t.HasCheckConstraint("CK_shipping_methods_market_code", "\"MarketCode\" IN ('SA','EG')");

                            t.HasCheckConstraint("CK_shipping_methods_name_lengths", "char_length(\"NameAr\") BETWEEN 1 AND 120 AND char_length(\"NameEn\") BETWEEN 1 AND 120");
                        });
                });

            modelBuilder.Entity("BackendApi.Modules.Shipping.Domain.ShippingMethodVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("EffectiveAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EligibilityJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("EtaMaxHours")
                        .HasColumnType("integer");

                    b.Property<int>("EtaMinHours")
                        .HasColumnType("integer");

                    b.Property<Guid>("MethodId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReviewerId")
                        .HasColumnType("uuid");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("VersionNo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MethodId", "State")
                        .HasDatabaseName("IX_method_versions_state");

                    b.HasIndex("MethodId", "VersionNo")
                        .IsUnique()
                        .HasDatabaseName("UX_method_versions_method_version_no");

                    b.ToTable("shipping_method_versions", "shipping", t =>
                        {
                            t.HasCheckConstraint("CK_method_versions_eta", "\"EtaMinHours\" >= 0 AND \"EtaMaxHours\" >= \"EtaMinHours\"");

                            t.HasCheckConstraint("CK_method_versions_reviewer_not_author", "\"PublishedAt\" IS NULL OR \"ReviewerId\" IS NULL OR \"ReviewerId\" <> \"AuthorId\"");

                            t.HasCheckConstraint("CK_method_versions_state", "\"State\" IN ('draft','in_review','published','archived')");

                            t.HasCheckConstraint("CK_method_versions_version_no", "\"VersionNo\" >= 1");
                        });
                });

            modelBuilder.Entity("BackendApi.Modules.Shipping.Domain.ShippingZone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("CityListJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MarketCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PostalCodePrefixesJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MarketCode", "DeletedAt")
                        .HasDatabaseName("IX_shipping_zones_market");

                    b.ToTable("shipping_zones", "shipping", t =>
                        {
                            t.HasCheckConstraint("CK_shipping_zones_market_code", "\"MarketCode\" IN ('SA','EG')");

                            t.HasCheckConstraint("CK_shipping_zones_name_lengths", "char_length(\"NameAr\") BETWEEN 1 AND 120 AND char_length(\"NameEn\") BETWEEN 1 AND 120");
                        });
                });

            modelBuilder.Entity("BackendApi.Modules.Shipping.Domain.WebhookReceived", b =>
                {
                    b.Property<string>("ProviderId")
                        .HasColumnType("text");

                    b.Property<string>("ProviderTrackingId")
                        .HasColumnType("text");

                    b.Property<string>("EventKind")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("SignatureValidated")
                        .HasColumnType("boolean");

                    b.HasKey("ProviderId", "ProviderTrackingId", "EventKind", "OccurredAt");

                    b.ToTable("webhooks_received", "shipping");
                });
#pragma warning restore 612, 618
        }
    }
}
