// <auto-generated />
using System;
using BackendApi.Modules.Identity.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BackendApi.Modules.Identity.Persistence.Migrations
{
    [DbContext(typeof(IdentityDbContext))]
    [Migration("20260423084937_Identity_AccountPermissionVersion")]
    partial class Identity_AccountPermissionVersion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("identity")
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BackendApi.Modules.Identity.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CompanyAccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<string>("EmailDisplay")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmailNormalized")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<DateTimeOffset?>("EmailVerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("citext")
                        .HasDefaultValue("ar");

                    b.Property<string>("MarketCode")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<short>("PasswordHashVersion")
                        .HasColumnType("smallint");

                    b.Property<int>("PermissionVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("PhoneE164")
                        .HasColumnType("text");

                    b.Property<string>("PhoneMarketCode")
                        .HasColumnType("citext");

                    b.Property<DateTimeOffset?>("PhoneVerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProfessionalVerificationStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("citext")
                        .HasDefaultValue("unverified");

                    b.Property<DateTimeOffset?>("ProfessionalVerificationStatusUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<string>("Surface")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CompanyAccountId");

                    b.HasIndex("MarketCode", "CreatedAt");

                    b.HasIndex("Surface", "EmailNormalized")
                        .IsUnique()
                        .HasFilter("\"DeletedAt\" IS NULL");

                    b.HasIndex("Surface", "PhoneE164")
                        .IsUnique()
                        .HasFilter("\"PhoneE164\" IS NOT NULL AND \"DeletedAt\" IS NULL");

                    b.ToTable("accounts", "identity");
                });

            modelBuilder.Entity("BackendApi.Modules.Identity.Entities.AccountRole", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<string>("MarketCode")
                        .HasColumnType("citext");

                    b.Property<DateTimeOffset>("GrantedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("GrantedByAccountId")
                        .HasColumnType("uuid");

                    b.HasKey("AccountId", "RoleId", "MarketCode");

                    b.ToTable("account_roles", "identity");
                });

            modelBuilder.Entity("BackendApi.Modules.Identity.Entities.AdminInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AcceptedAccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EmailNormalized")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InvitedByAccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("InvitedRoleId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.ToTable("admin_invitations", "identity");
                });

            modelBuilder.Entity("BackendApi.Modules.Identity.Entities.AdminMfaFactor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ProvisioningTokenExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("ProvisioningTokenHash")
                        .HasColumnType("bytea");

                    b.Property<string>("RecoveryCodesHash")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("SecretEncrypted")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "Kind")
                        .IsUnique()
                        .HasFilter("\"RevokedAt\" IS NULL");

                    b.ToTable("admin_mfa_factors", "identity");
                });

            modelBuilder.Entity("BackendApi.Modules.Identity.Entities.AdminMfaReplayGuard", b =>
                {
                    b.Property<Guid>("FactorId")
                        .HasColumnType("uuid");

                    b.Property<long>("WindowCounter")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("ObservedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("FactorId", "WindowCounter");

                    b.ToTable("admin_mfa_replay_guard", "identity");
                });

            modelBuilder.Entity("BackendApi.Modules.Identity.Entities.AuthorizationAudit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PermissionCode")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<string>("Surface")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.HasKey("Id");

                    b.HasIndex("Surface", "PermissionCode", "Decision", "OccurredAt");

                    b.ToTable("authorization_audit", "identity");
                });

            modelBuilder.Entity("BackendApi.Modules.Identity.Entities.EmailVerificationChallenge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<Guid?>("TokenId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("TokenSecretHash")
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("TokenId")
                        .IsUnique()
                        .HasFilter("\"TokenId\" IS NOT NULL");

                    b.ToTable("email_verification_challenges", "identity");
                });

            modelBuilder.Entity("BackendApi.Modules.Identity.Entities.LockoutState", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .HasColumnType("citext");

                    b.Property<int>("CooldownIndex")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("FailedCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("FirstFailedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LockedUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("RequiresAdminUnlock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("Tier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("AccountId", "Reason");

                    b.ToTable("lockout_state", "identity");
                });

            modelBuilder.Entity("BackendApi.Modules.Identity.Entities.OtpChallenge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<short>("Attempts")
                        .HasColumnType("smallint");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<byte[]>("CodeHash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<short>("CodeLength")
                        .HasColumnType("smallint");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("DestinationHash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short>("MaxAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)3);

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<string>("Surface")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "Purpose", "CreatedAt");

                    b.ToTable("otp_challenges", "identity");
                });

            modelBuilder.Entity("BackendApi.Modules.Identity.Entities.PasswordResetToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<Guid?>("TokenId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("TokenSecretHash")
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("TokenId")
                        .IsUnique()
                        .HasFilter("\"TokenId\" IS NOT NULL");

                    b.ToTable("password_reset_tokens", "identity");
                });

            modelBuilder.Entity("BackendApi.Modules.Identity.Entities.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("permissions", "identity");
                });

            modelBuilder.Entity("BackendApi.Modules.Identity.Entities.RateLimitEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("BlockedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PolicyCode")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<byte[]>("ScopeKeyHash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("Surface")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.HasKey("Id");

                    b.HasIndex("PolicyCode", "BlockedAt");

                    b.ToTable("rate_limit_events", "identity");
                });

            modelBuilder.Entity("BackendApi.Modules.Identity.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<Guid?>("SupersededBy")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("TokenHash")
                        .HasColumnType("bytea");

                    b.Property<Guid?>("TokenId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("TokenSecretHash")
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("SessionId")
                        .IsUnique()
                        .HasFilter("\"Status\" = 'active'");

                    b.HasIndex("TokenId")
                        .IsUnique()
                        .HasFilter("\"TokenId\" IS NOT NULL");

                    b.ToTable("refresh_tokens", "identity");
                });

            modelBuilder.Entity("BackendApi.Modules.Identity.Entities.RevokedRefreshToken", b =>
                {
                    b.Property<byte[]>("TokenHash")
                        .HasColumnType("bytea");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<DateTimeOffset>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TokenHash");

                    b.ToTable("revoked_refresh_tokens", "identity");
                });

            modelBuilder.Entity("BackendApi.Modules.Identity.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<bool>("System")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("roles", "identity");
                });

            modelBuilder.Entity("BackendApi.Modules.Identity.Entities.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid");

                    b.HasKey("RoleId", "PermissionId");

                    b.ToTable("role_permissions", "identity");
                });

            modelBuilder.Entity("BackendApi.Modules.Identity.Entities.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("ClientAgent")
                        .HasColumnType("text");

                    b.Property<byte[]>("ClientFingerprintHash")
                        .HasColumnType("bytea");

                    b.Property<byte[]>("ClientIpHash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RevokedReason")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<string>("Surface")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "Status", "LastSeenAt");

                    b.ToTable("sessions", "identity");
                });
#pragma warning restore 612, 618
        }
    }
}
