// <auto-generated />
using System;
using BackendApi.Modules.Pricing.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BackendApi.Modules.Pricing.Persistence.Migrations
{
    [DbContext(typeof(PricingDbContext))]
    [Migration("20260503033314_Pricing_007b_CommercialAuthoring")]
    partial class Pricing_007b_CommercialAuthoring
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("pricing")
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BackendApi.Modules.Pricing.Entities.AccountB2BTier", b =>
                {
                    b.Property<Guid>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("AssignedByAccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TierId")
                        .HasColumnType("uuid");

                    b.HasKey("AccountId");

                    b.ToTable("account_b2b_tiers", "pricing");
                });

            modelBuilder.Entity("BackendApi.Modules.Pricing.Entities.B2BTier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DefaultDiscountBps")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("b2b_tiers", "pricing");
                });

            modelBuilder.Entity("BackendApi.Modules.Pricing.Entities.BundleMembership", b =>
                {
                    b.Property<Guid>("BundleProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ComponentProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("Qty")
                        .HasColumnType("integer");

                    b.HasKey("BundleProductId", "ComponentProductId");

                    b.ToTable("bundle_memberships", "pricing");
                });

            modelBuilder.Entity("BackendApi.Modules.Pricing.Entities.Campaign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LandingQuery")
                        .HasMaxLength(1024)
                        .HasColumnType("text");

                    b.Property<bool>("LinkBroken")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.PrimitiveCollection<string[]>("Markets")
                        .IsRequired()
                        .HasColumnType("citext[]");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("text");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("text");

                    b.Property<string>("NotesInternal")
                        .HasMaxLength(4000)
                        .HasColumnType("text");

                    b.Property<int>("State")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("State");

                    b.Property<DateTimeOffset>("StateChangedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("StateChangedByActorId")
                        .HasColumnType("uuid");

                    b.Property<string>("StateChangedReasonNote")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ValidFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ValidTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("VendorId")
                        .HasColumnType("uuid");

                    b.Property<uint>("XminRowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("State")
                        .HasDatabaseName("IX_campaigns_state_active_or_scheduled")
                        .HasFilter("\"State\" IN (1, 2)");

                    b.HasIndex("ValidFrom")
                        .HasDatabaseName("IX_campaigns_valid_from");

                    b.HasIndex("VendorId")
                        .HasDatabaseName("IX_campaigns_vendor_id");

                    b.ToTable("campaigns", "pricing", t =>
                        {
                            t.HasCheckConstraint("chk_campaign_markets_non_empty", "array_length(\"Markets\", 1) >= 1");

                            t.HasCheckConstraint("chk_campaign_valid_window", "\"ValidTo\" > \"ValidFrom\"");
                        });
                });

            modelBuilder.Entity("BackendApi.Modules.Pricing.Entities.CampaignLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<DateTimeOffset?>("LinkBrokenAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("TargetId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId")
                        .IsUnique()
                        .HasDatabaseName("UX_campaign_links_active_per_campaign")
                        .HasFilter("\"LinkBrokenAtUtc\" IS NULL");

                    b.HasIndex("Kind", "TargetId")
                        .HasDatabaseName("IX_campaign_links_kind_target");

                    b.ToTable("campaign_links", "pricing", t =>
                        {
                            t.HasCheckConstraint("chk_campaign_link_kind", "\"Kind\"::text IN ('promotion','coupon','landing_only')");

                            t.HasCheckConstraint("chk_campaign_link_target_required", "(\"Kind\"::text = 'landing_only' AND \"TargetId\" IS NULL) OR (\"Kind\"::text <> 'landing_only' AND \"TargetId\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("BackendApi.Modules.Pricing.Entities.CommercialApproval", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ApprovedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ApproverActorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorActorId")
                        .HasColumnType("uuid");

                    b.Property<string>("CosignNote")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TargetEntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("TargetEntityKind")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<uint>("XminRowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("TargetEntityKind", "TargetEntityId")
                        .IsUnique()
                        .HasDatabaseName("UX_commercial_approvals_target");

                    b.ToTable("commercial_approvals", "pricing", t =>
                        {
                            t.HasCheckConstraint("chk_approval_note_min_length", "char_length(\"CosignNote\") >= 10");

                            t.HasCheckConstraint("chk_approval_separation_of_duties", "\"ApproverActorId\" <> \"AuthorActorId\"");

                            t.HasCheckConstraint("chk_approval_target_kind", "\"TargetEntityKind\"::text IN ('coupon','promotion')");
                        });
                });

            modelBuilder.Entity("BackendApi.Modules.Pricing.Entities.CommercialAuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid");

                    b.Property<string>("ActorRole")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<string>("AfterJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("BeforeJson")
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<string>("DiffJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<string>("ReasonNote")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("RecordedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TargetEntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("TargetEntityKind")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.HasKey("Id");

                    b.HasIndex("ActorId", "RecordedAtUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_cae_actor");

                    b.HasIndex("TargetEntityKind", "TargetEntityId", "RecordedAtUtc")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("IX_cae_target");

                    b.ToTable("commercial_audit_events", "pricing", t =>
                        {
                            t.HasCheckConstraint("chk_cae_target_kind", "\"TargetEntityKind\"::text IN ('coupon','promotion','campaign','business_pricing','preview_profile','commercial_threshold','commercial_approval')");
                        });
                });

            modelBuilder.Entity("BackendApi.Modules.Pricing.Entities.CommercialThreshold", b =>
                {
                    b.Property<string>("MarketCode")
                        .HasColumnType("citext");

                    b.Property<int>("CouponInFlightGraceSeconds")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1800);

                    b.Property<bool>("GateEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("PromotionInFlightGraceSeconds")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1800);

                    b.Property<long?>("ThresholdAmountOffMinor")
                        .HasColumnType("bigint");

                    b.Property<int?>("ThresholdDurationDays")
                        .HasColumnType("integer");

                    b.Property<decimal?>("ThresholdPercentOff")
                        .HasColumnType("numeric(5,2)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UpdatedByActorId")
                        .HasColumnType("uuid");

                    b.Property<uint>("XminRowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("MarketCode");

                    b.ToTable("commercial_thresholds", "pricing", t =>
                        {
                            t.HasCheckConstraint("chk_thr_amount_off", "\"ThresholdAmountOffMinor\" IS NULL OR \"ThresholdAmountOffMinor\" >= 0");

                            t.HasCheckConstraint("chk_thr_coupon_grace", "\"CouponInFlightGraceSeconds\" >= 300 AND \"CouponInFlightGraceSeconds\" <= 7200");

                            t.HasCheckConstraint("chk_thr_duration", "\"ThresholdDurationDays\" IS NULL OR \"ThresholdDurationDays\" >= 0");

                            t.HasCheckConstraint("chk_thr_market", "\"MarketCode\"::text IN ('SA','EG')");

                            t.HasCheckConstraint("chk_thr_pct_off", "\"ThresholdPercentOff\" IS NULL OR (\"ThresholdPercentOff\" >= 0 AND \"ThresholdPercentOff\" <= 100)");

                            t.HasCheckConstraint("chk_thr_promo_grace", "\"PromotionInFlightGraceSeconds\" >= 300 AND \"PromotionInFlightGraceSeconds\" <= 7200");
                        });
                });

            modelBuilder.Entity("BackendApi.Modules.Pricing.Entities.Coupon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AppliesToBroken")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset?>("AppliesToBrokenAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("CapMinor")
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("DisplayInBanners")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("ExcludesRestricted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.PrimitiveCollection<string[]>("MarketCodes")
                        .IsRequired()
                        .HasColumnType("citext[]");

                    b.Property<int?>("OverallLimit")
                        .HasColumnType("integer");

                    b.Property<string>("OwnerId")
                        .HasColumnType("citext");

                    b.Property<int?>("PerCustomerLimit")
                        .HasColumnType("integer");

                    b.Property<int>("State")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("State");

                    b.Property<DateTimeOffset>("StateChangedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("StateChangedByActorId")
                        .HasColumnType("uuid");

                    b.Property<string>("StateChangedReasonNote")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UsedCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("ValidFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ValidTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.Property<Guid?>("VendorId")
                        .HasColumnType("uuid");

                    b.Property<uint>("XminRowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("AppliesToBroken")
                        .HasDatabaseName("IX_coupons_applies_to_broken")
                        .HasFilter("\"AppliesToBroken\" = TRUE");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("State")
                        .HasDatabaseName("IX_coupons_state");

                    b.HasIndex("VendorId")
                        .HasDatabaseName("IX_coupons_vendor_id");

                    b.ToTable("coupons", "pricing");
                });

            modelBuilder.Entity("BackendApi.Modules.Pricing.Entities.CouponRedemption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CouponId")
                        .HasColumnType("uuid");

                    b.Property<string>("MarketCode")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("RedeemedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CouponId", "AccountId")
                        .IsUnique()
                        .HasDatabaseName("IX_coupon_redemptions_coupon_account_order_null")
                        .HasFilter("\"OrderId\" IS NULL");

                    b.HasIndex("CouponId", "AccountId", "OrderId")
                        .IsUnique()
                        .HasDatabaseName("IX_coupon_redemptions_coupon_account_order_not_null")
                        .HasFilter("\"OrderId\" IS NOT NULL");

                    b.ToTable("coupon_redemptions", "pricing");
                });

            modelBuilder.Entity("BackendApi.Modules.Pricing.Entities.PreviewProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccountKind")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<string>("CartLinesJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<string>("MarketCode")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("text");

                    b.Property<Guid?>("TierId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("VendorId")
                        .HasColumnType("uuid");

                    b.Property<string>("VerificationState")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("citext")
                        .HasDefaultValue("personal");

                    b.Property<uint>("XminRowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("IX_preview_profiles_personal_by_creator")
                        .HasFilter("\"Visibility\"::text = 'personal'");

                    b.HasIndex("Visibility")
                        .HasDatabaseName("IX_preview_profiles_shared")
                        .HasFilter("\"Visibility\"::text = 'shared'");

                    b.ToTable("preview_profiles", "pricing", t =>
                        {
                            t.HasCheckConstraint("chk_preview_profile_account_kind", "\"AccountKind\"::text IN ('consumer','b2b')");

                            t.HasCheckConstraint("chk_preview_profile_locale", "\"Locale\"::text IN ('ar','en')");

                            t.HasCheckConstraint("chk_preview_profile_market", "\"MarketCode\"::text IN ('SA','EG')");

                            t.HasCheckConstraint("chk_preview_profile_verification_state", "\"VerificationState\"::text IN ('none','submitted','approved','rejected','expired')");

                            t.HasCheckConstraint("chk_preview_profile_visibility", "\"Visibility\"::text IN ('personal','shared')");
                        });
                });

            modelBuilder.Entity("BackendApi.Modules.Pricing.Entities.PriceExplanation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("ExplanationHash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("ExplanationJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<long>("GrandTotalMinor")
                        .HasColumnType("bigint");

                    b.Property<string>("MarketCode")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("OwnerKind")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.HasKey("Id");

                    b.HasIndex("OwnerKind", "OwnerId")
                        .IsUnique()
                        .HasFilter("\"OwnerKind\" IN ('quote','order')");

                    b.ToTable("price_explanations", "pricing");
                });

            modelBuilder.Entity("BackendApi.Modules.Pricing.Entities.ProductTierPrice", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TierId")
                        .HasColumnType("uuid");

                    b.Property<string>("MarketCode")
                        .HasColumnType("citext");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<bool>("CompanyLinkBroken")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset?>("CompanyLinkBrokenAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CopiedFromTierId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("NetMinor")
                        .HasColumnType("bigint");

                    b.Property<int>("State")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("State");

                    b.Property<DateTimeOffset>("StateChangedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("StateChangedByActorId")
                        .HasColumnType("uuid");

                    b.Property<string>("StateChangedReasonNote")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("VendorId")
                        .HasColumnType("uuid");

                    b.Property<uint>("XminRowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("ProductId", "TierId", "MarketCode");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("IX_product_tier_prices_company_id");

                    b.HasIndex("CompanyLinkBroken")
                        .HasDatabaseName("IX_product_tier_prices_company_link_broken")
                        .HasFilter("\"CompanyLinkBroken\" = TRUE");

                    b.HasIndex("VendorId")
                        .HasDatabaseName("IX_product_tier_prices_vendor_id");

                    b.ToTable("product_tier_prices", "pricing");
                });

            modelBuilder.Entity("BackendApi.Modules.Pricing.Entities.Promotion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AppliesToBroken")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset?>("AppliesToBrokenAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<Guid[]>("AppliesToCategoryIds")
                        .HasColumnType("uuid[]");

                    b.PrimitiveCollection<Guid[]>("AppliesToProductIds")
                        .HasColumnType("uuid[]");

                    b.Property<bool>("BannerEligible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("EndsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.PrimitiveCollection<string[]>("MarketCodes")
                        .IsRequired()
                        .HasColumnType("citext[]");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OwnerId")
                        .HasColumnType("citext");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("StartsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("State")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("State");

                    b.Property<DateTimeOffset>("StateChangedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("StateChangedByActorId")
                        .HasColumnType("uuid");

                    b.Property<string>("StateChangedReasonNote")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("VendorId")
                        .HasColumnType("uuid");

                    b.Property<uint>("XminRowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("AppliesToBroken")
                        .HasDatabaseName("IX_promotions_applies_to_broken")
                        .HasFilter("\"AppliesToBroken\" = TRUE");

                    b.HasIndex("Priority");

                    b.HasIndex("State")
                        .HasDatabaseName("IX_promotions_state");

                    b.HasIndex("VendorId")
                        .HasDatabaseName("IX_promotions_vendor_id");

                    b.HasIndex("IsActive", "DeletedAt");

                    b.ToTable("promotions", "pricing");
                });

            modelBuilder.Entity("BackendApi.Modules.Pricing.Entities.TaxRate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByAccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("EffectiveTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<string>("MarketCode")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<int>("RateBps")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MarketCode", "Kind", "EffectiveFrom")
                        .IsUnique();

                    b.ToTable("tax_rates", "pricing");
                });

            modelBuilder.Entity("BackendApi.Modules.Pricing.Entities.CampaignLink", b =>
                {
                    b.HasOne("BackendApi.Modules.Pricing.Entities.Campaign", null)
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
