// <auto-generated />
using System;
using BackendApi.Modules.Pricing.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BackendApi.Modules.Pricing.Persistence.Migrations
{
    [DbContext(typeof(PricingDbContext))]
    [Migration("20260423221137_Pricing_Initial")]
    partial class Pricing_Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("pricing")
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BackendApi.Modules.Pricing.Entities.AccountB2BTier", b =>
                {
                    b.Property<Guid>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("AssignedByAccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TierId")
                        .HasColumnType("uuid");

                    b.HasKey("AccountId");

                    b.ToTable("account_b2b_tiers", "pricing");
                });

            modelBuilder.Entity("BackendApi.Modules.Pricing.Entities.B2BTier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DefaultDiscountBps")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("b2b_tiers", "pricing");
                });

            modelBuilder.Entity("BackendApi.Modules.Pricing.Entities.BundleMembership", b =>
                {
                    b.Property<Guid>("BundleProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ComponentProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("Qty")
                        .HasColumnType("integer");

                    b.HasKey("BundleProductId", "ComponentProductId");

                    b.ToTable("bundle_memberships", "pricing");
                });

            modelBuilder.Entity("BackendApi.Modules.Pricing.Entities.Coupon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long?>("CapMinor")
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("ExcludesRestricted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.PrimitiveCollection<string[]>("MarketCodes")
                        .IsRequired()
                        .HasColumnType("citext[]");

                    b.Property<int?>("OverallLimit")
                        .HasColumnType("integer");

                    b.Property<string>("OwnerId")
                        .HasColumnType("citext");

                    b.Property<int?>("PerCustomerLimit")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UsedCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("ValidFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ValidTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.Property<Guid?>("VendorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("coupons", "pricing");
                });

            modelBuilder.Entity("BackendApi.Modules.Pricing.Entities.CouponRedemption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CouponId")
                        .HasColumnType("uuid");

                    b.Property<string>("MarketCode")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("RedeemedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CouponId", "AccountId")
                        .IsUnique()
                        .HasDatabaseName("IX_coupon_redemptions_coupon_account_order_null")
                        .HasFilter("\"OrderId\" IS NULL");

                    b.HasIndex("CouponId", "AccountId", "OrderId")
                        .IsUnique()
                        .HasDatabaseName("IX_coupon_redemptions_coupon_account_order_not_null")
                        .HasFilter("\"OrderId\" IS NOT NULL");

                    b.ToTable("coupon_redemptions", "pricing");
                });

            modelBuilder.Entity("BackendApi.Modules.Pricing.Entities.PriceExplanation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("ExplanationHash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("ExplanationJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<long>("GrandTotalMinor")
                        .HasColumnType("bigint");

                    b.Property<string>("MarketCode")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("OwnerKind")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.HasKey("Id");

                    b.HasIndex("OwnerKind", "OwnerId")
                        .IsUnique()
                        .HasFilter("\"OwnerKind\" IN ('quote','order')");

                    b.ToTable("price_explanations", "pricing");
                });

            modelBuilder.Entity("BackendApi.Modules.Pricing.Entities.ProductTierPrice", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TierId")
                        .HasColumnType("uuid");

                    b.Property<string>("MarketCode")
                        .HasColumnType("citext");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("NetMinor")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ProductId", "TierId", "MarketCode");

                    b.ToTable("product_tier_prices", "pricing");
                });

            modelBuilder.Entity("BackendApi.Modules.Pricing.Entities.Promotion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<Guid[]>("AppliesToCategoryIds")
                        .HasColumnType("uuid[]");

                    b.PrimitiveCollection<Guid[]>("AppliesToProductIds")
                        .HasColumnType("uuid[]");

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("EndsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.PrimitiveCollection<string[]>("MarketCodes")
                        .IsRequired()
                        .HasColumnType("citext[]");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OwnerId")
                        .HasColumnType("citext");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("StartsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("VendorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Priority");

                    b.HasIndex("IsActive", "DeletedAt");

                    b.ToTable("promotions", "pricing");
                });

            modelBuilder.Entity("BackendApi.Modules.Pricing.Entities.TaxRate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByAccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("EffectiveTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<string>("MarketCode")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<int>("RateBps")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MarketCode", "Kind", "EffectiveFrom")
                        .IsUnique();

                    b.ToTable("tax_rates", "pricing");
                });
#pragma warning restore 612, 618
        }
    }
}
