// <auto-generated />
using System;
using BackendApi.Modules.Checkout.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BackendApi.Modules.Checkout.Persistence.Migrations
{
    [DbContext(typeof(CheckoutDbContext))]
    partial class CheckoutDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("checkout")
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BackendApi.Modules.Checkout.Entities.CheckoutSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("AcceptedDriftAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("BillingAddressJson")
                        .HasColumnType("jsonb");

                    b.Property<Guid>("CartId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("CartTokenHash")
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CouponCode")
                        .HasColumnType("citext");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ExpiredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("FailedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FailureReasonCode")
                        .HasColumnType("citext");

                    b.Property<Guid?>("IssuedExplanationId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("LastPreviewHash")
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset>("LastTouchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MarketCode")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("citext");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("ShippingAddressJson")
                        .HasColumnType("jsonb");

                    b.Property<long?>("ShippingFeeMinor")
                        .HasColumnType("bigint");

                    b.Property<string>("ShippingMethodCode")
                        .HasColumnType("citext");

                    b.Property<string>("ShippingProviderId")
                        .HasColumnType("citext");

                    b.Property<string>("State")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("citext")
                        .HasDefaultValue("init");

                    b.Property<DateTimeOffset?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("MarketCode");

                    b.HasIndex("State", "ExpiresAt")
                        .HasDatabaseName("IX_checkout_sessions_state_expires");

                    b.HasIndex("AccountId", "State", "LastTouchedAt")
                        .HasDatabaseName("IX_checkout_sessions_account_state_touched");

                    b.ToTable("sessions", "checkout", t =>
                        {
                            t.HasCheckConstraint("CK_checkout_sessions_identity_present", "\"AccountId\" IS NOT NULL OR \"CartTokenHash\" IS NOT NULL");

                            t.HasCheckConstraint("CK_checkout_sessions_state_enum", "\"State\" IN ('init','addressed','shipping_selected','payment_selected','submitted','confirmed','failed','expired')");
                        });
                });

            modelBuilder.Entity("BackendApi.Modules.Checkout.Entities.IdempotencyResult", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("RequestFingerprint")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("ResponseJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<int>("ResponseStatus")
                        .HasColumnType("integer");

                    b.HasKey("AccountId", "IdempotencyKey");

                    b.HasIndex("ExpiresAt");

                    b.ToTable("idempotency_results", "checkout");
                });

            modelBuilder.Entity("BackendApi.Modules.Checkout.Entities.PaymentAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("AmountMinor")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<string>("ErrorCode")
                        .HasColumnType("text");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<string>("ProviderTxnId")
                        .HasColumnType("text");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("State")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("citext")
                        .HasDefaultValue("initiated");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProviderId", "ProviderTxnId");

                    b.HasIndex("SessionId", "CreatedAt");

                    b.ToTable("payment_attempts", "checkout", t =>
                        {
                            t.HasCheckConstraint("CK_checkout_payment_attempts_amount_non_negative", "\"AmountMinor\" >= 0");

                            t.HasCheckConstraint("CK_checkout_payment_attempts_state_enum", "\"State\" IN ('initiated','authorized','captured','declined','voided','failed','refunded','pending_webhook')");
                        });
                });

            modelBuilder.Entity("BackendApi.Modules.Checkout.Entities.PaymentWebhookEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<DateTimeOffset?>("HandledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProviderEventId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<string>("RawPayload")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("SignatureVerified")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ReceivedAt");

                    b.HasIndex("ProviderId", "ProviderEventId")
                        .IsUnique();

                    b.ToTable("payment_webhook_events", "checkout");
                });

            modelBuilder.Entity("BackendApi.Modules.Checkout.Entities.ShippingQuote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<int>("EtaMaxDays")
                        .HasColumnType("integer");

                    b.Property<int>("EtaMinDays")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("FeeMinor")
                        .HasColumnType("bigint");

                    b.Property<string>("MethodCode")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "ExpiresAt");

                    b.ToTable("shipping_quotes", "checkout", t =>
                        {
                            t.HasCheckConstraint("CK_checkout_shipping_quotes_eta_max_ge_min", "\"EtaMaxDays\" >= \"EtaMinDays\"");

                            t.HasCheckConstraint("CK_checkout_shipping_quotes_eta_min_non_negative", "\"EtaMinDays\" >= 0");

                            t.HasCheckConstraint("CK_checkout_shipping_quotes_fee_non_negative", "\"FeeMinor\" >= 0");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
